# ############################################### #
# GNU Make file for framewidget
#
# Mandatory Vars to be exported from here
#	PROJECT,DIRDEPTH
# ############################################### #

# -- the target
export PROJECT=framewidget
export DIRDEPTH = ..

WIDGETSDIR=../widgets
EXTRASOURCES=AEEBase.c
EXTRAHEADERS=AEEBase.h

# -- additional lint suppression files
LINT_SUPPRESSION_FILES=$(WIDGETSDIR)/lint/_project.lnt

### include generic makefile ###
include $(DIRDEPTH)/ext.mak
