#ifndef _DAVINCICODE_
#define _DAVINCICODE_

#include "mmp_rdk.h"

#define CORE_RELEASE	 	1
#define LOAD_CORE_FILE	0
#define LOAD_CORE_FILE_USB			0
#define LOAD_CORE_FILE_REC_AMR	0
#define LOAD_CORE_FILE_REC_MP3	0
#define LOAD_CORE_FILE_MEDIAPLAY	0
#define LOAD_CORE_FILE_CMMB		0
#define LOAD_CORE_FILE_RV			0
#define LOAD_CORE_FILE_RVOVERLAY	0

#if CORE_RELEASE

#define	V8XXCORE_USB_INCLUDE		1
#if V8XXCORE_USB_INCLUDE
extern __align(32) MMD_S08 V8XXCORE_USB_START[85844];
#else
extern __align(32) MMD_S08 V8XXCORE_USB_START[4];
#endif

#define	V8XXCORE_MEDIAREC_INCLUDE		1
#if V8XXCORE_MEDIAREC_INCLUDE
extern __align(32) MMD_S08 V8XXCORE_MEDIAREC_START[138528];
#else
extern __align(32) MMD_S08 V8XXCORE_MEDIAREC_START[4];
#endif

#define	V8XXCORE_MP3REC_INCLUDE		1
#if V8XXCORE_MP3REC_INCLUDE
extern __align(32) MMD_S08 V8XXCORE_MP3REC_START[108236];
#else
extern __align(32) MMD_S08 V8XXCORE_MP3REC_START[4];
#endif

#define	SRAM_EXEC_ROM_INCLUDE		1
#if SRAM_EXEC_ROM_INCLUDE
extern __align(32) MMD_S08 SRAM_EXEC_ROM_START[85644];
#else
extern __align(32) MMD_S08 SRAM_EXEC_ROM_START[4];
#endif

#define	EXEC_SAMR_INCLUDE		1
#if EXEC_SAMR_INCLUDE
extern __align(32) MMD_S08 EXEC_SAMR_START[158140];
#else
extern __align(32) MMD_S08 EXEC_SAMR_START[4];
#endif

#define	V8XXCORE_CMMB_INCLUDE		0
#if V8XXCORE_CMMB_INCLUDE
extern __align(32) MMD_S08 V8XXCORE_CMMB_START[3];
#else
extern __align(32) MMD_S08 V8XXCORE_CMMB_START[4];
#endif

#define	RV_SDRAM_EXEC_ROM_INCLUDE		0
#if RV_SDRAM_EXEC_ROM_INCLUDE
extern __align(32) MMD_S08 RV_SDRAM_EXEC_ROM_START[3];
#else
extern __align(32) MMD_S08 RV_SDRAM_EXEC_ROM_START[4];
#endif

#define	RV9_EXEC_INCLUDE		0
#if RV9_EXEC_INCLUDE
extern __align(32) MMD_S08 RV9_EXEC_START[3];
#else
extern __align(32) MMD_S08 RV9_EXEC_START[4];
#endif

#define	RV8_EXEC_INCLUDE		0
#if RV8_EXEC_INCLUDE
extern __align(32) MMD_S08 RV8_EXEC_START[3];
#else
extern __align(32) MMD_S08 RV8_EXEC_START[4];
#endif

#define	RVG2_EXEC_INCLUDE		0
#if RVG2_EXEC_INCLUDE
extern __align(32) MMD_S08 RVG2_EXEC_START[3];
#else
extern __align(32) MMD_S08 RVG2_EXEC_START[4];
#endif


#if 0
extern DWORD_ALIGN MMD_S08 VC0848_CODE_USB_START[4];

extern DWORD_ALIGN MMD_S08 VC0848_CODE_REC_AMR_START[4];

extern DWORD_ALIGN MMD_S08 VC0848_CODE_MEDIA_PLAY_START[69976];

extern DWORD_ALIGN MMD_S08 VC0848_CODE_DECODER_START[157248];
#endif

/*extern DWORD_ALIGN MMD_S08 VC0848_CODE_CMMB_START[478836];
#else
extern DWORD_ALIGN MMD_S08 VC0848_CODE_CMMB_START[471748];
#endif
extern DWORD_ALIGN MMD_S08 VC0848_CODE_RV_START[639300];*/

#else
extern MMD_S08 V8XXCORE_USB_START[];
extern MMD_S08 V8XXCORE_USB_END[];
extern MMD_S08 V8XXCORE_MEDIAREC_START[];
extern MMD_S08 V8XXCORE_MEDIAREC_END[];
extern MMD_S08 V8XXCORE_MP3REC_START[];
extern MMD_S08 V8XXCORE_MP3REC_END[];
extern MMD_S08 SRAM_EXEC_ROM_START[];
extern MMD_S08 SRAM_EXEC_ROM_END[];
extern MMD_S08 EXEC_SAMR_START[];
extern MMD_S08 EXEC_SAMR_END[];
extern MMD_S08 V8XXCORE_CMMB_START[];
extern MMD_S08 V8XXCORE_CMMB_END[];
extern MMD_S08 V8XXCORE_RV_START[];
extern MMD_S08 V8XXCORE_RV_END[];
extern MMD_S08 RV_SDRAM_EXEC_ROM_START[];
extern MMD_S08 RV_SDRAM_EXEC_ROM_END[];
extern MMD_S08 RV9_EXEC_START[];
extern MMD_S08 RV9_EXEC_END[];
extern MMD_S08 RV8_EXEC_START[];
extern MMD_S08 RV8_EXEC_END[];
extern MMD_S08 RVG2_EXEC_START[];
extern MMD_S08 RVG2_EXEC_END[];
extern MMD_S08 RV20_EXEC_START[];
extern MMD_S08 RV20_EXEC_END[];
		
#endif


extern MMD_S08 TEST_FILE_START[];
extern MMD_S08 TEST_FILE_END[];

typedef enum _SCENE_IDX
{
	SCENE_USB=0,
	SCENE_REC_AMR	,	
	SCENE_REC_MP3	,	
	SCENE_MEDIAPLAY,
	SCENE_CMMB,
	SCENE_RV_OVERLAY,
	SCENE_RV20, // RV 2.0 version
	
	SCENE_UNCHANGED,
	SCENE_NUM,
	SCENE_IDX_RESERVED=0X7FFFFFFF	
}SCENE_IDX;
typedef enum _CODEC_IDX
{
	CODEC_SAMR = 0,
	CODEC_MP4A,
	CODEC_MP3,
	CODEC_AAC,
	CODEC_AMR,
	CODEC_IMA,
	CODEC_PCM,
	CODEC_MID,
	
	CODEC_UNCHANGED,	
	CODEC_NUM,
	CODEC_IDX_RESERVED=0X7FFFFFFF	
}CODEC_IDX;

typedef enum _RV_CODEC_IDX
{
	RV_CODEC_RV9 = 0,
	RV_CODEC_RV8,
	RV_CODEC_RVG2,

	RV_CODEC_NUM,
	RV_CODEC_IDX_RESERVED=0X7FFFFFFF	
}RV_CODEC_IDX;

typedef struct _CODE_MAP_INFO
{
	MMD_U32	RORW_Load_base;
	MMD_U32	RORW_Image_base;
	MMD_U32	RORW_Image_limit;
	MMD_U32	ZI_Image_base;
	MMD_U32	ZI_Image_limit;
}CODE_MAP_INFO, *pCODE_MAP_INFO;

typedef struct _SCENE_CODE_INFO
{
	MMD_U32   Scene_type;
	MMD_S08* StartAddr;
	MMD_U32 CodeLen;
}SCENE_CODE_INFO, *pSCENE_CODE_INFO;

#define SRAM_START_ADDR     0x20000000      // SRAM

#endif /* _DAVINCICODE_ */
