/*=============================================================================
   P R O G R E S S I V E   B O O T   E L F   G E N E R A T I O N   T O O L

   This program takes in an ELF file, a scatter load file and generates an
   ELF file in the progressive boot format and a hash table. The hash table
   will need to be signed for secure boot, and the header has to be generated
   before the final image can be created using pboot_add_hash.


EXTERNALIZED FUNCTIONS

INITIALIZATION AND SEQUENCING REQUIREMENTS

Copyright (c) 2007 by QUALCOMM, Inc.  All Rights Reserved.
=============================================================================*/

/*=============================================================================

                            EDIT HISTORY FOR MODULE

  This section contains comments describing changes made to the module.
  Notice that changes are listed in reverse chronological order.
//depot/asic/qsc6270/temp_dev/tools/headergen/pboot_hash2C.c#2

when       who     what, where, why
--------   ---     ------------------------------------------------------------
09/22/06   rjain   Removed an undefined variable that was being used in a printf
                   Strangely it did not show up as an error during compilation
                   on most of the systems.

=============================================================================*/


/*=============================================================================

                            INCLUDE FILES FOR MODULE

=============================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/types.h>
#include <unistd.h>
#include "pboot_elf_utils.h"
#include "pboot_gen_hash.h"

/*=============================================================================

            LOCAL DEFINITIONS AND DECLARATIONS FOR MODULE

=============================================================================*/

static const char FSBL_HASH[] = "fsbl_hash.c\0";/* FSBL hash file name */

/*=============================================================================

                              FUNCTION DEFINITIONS

=============================================================================*/

/*===========================================================================
FUNCTION  PRINT_USAGE

DESCRIPTION
    This function prints out the program usage

DEPENDENCIES

RETURN VALUE

SIDE EFFECTS

===========================================================================*/

void print_usage(char *filename)
{
  printf("This program takes in an hash file\n"
         "and generates an C file with array fsbl_hash[].\n"
         "Usage: %s inHashFile outCFile\n"
         "      inHashFile - input hash file generated by the pboot_gen_elf tool\n"
         "      outCFile  - output C file with hash array\n", filename);

}

/*===========================================================================

FUNCTION  write_hash

DESCRIPTION
    1) Get hash data and write into array

DEPENDENCIES
    1) Hash data already generated by pboot_gen_elf tool. If not, the array will be empty

RETURN VALUE

SIDE EFFECTS
    None.

===========================================================================*/
int write_hash
(
FILE *infile,   /* input elf file.  */
FILE *hashfp    /* output hash file */
)
{
  byte hash[PROG_BOOT_DIGEST_SIZE];

  if ( fread(hash, 1, PROG_BOOT_DIGEST_SIZE, infile) == 0 )
  {
    printf("Cannot read  from file!");
    return errno;
  }

  /* Write hash to file */

  fprintf(hashfp, "#include \"boot_comdef.h\"\n\n");
  fprintf(hashfp, "const byte fsbl_hash[] = {\n");

  int i=0;
  for ( i; i < PROG_BOOT_DIGEST_SIZE; i++ )
  {
    fprintf(hashfp,"0x%X%s\n", hash[i], (i < PROG_BOOT_DIGEST_SIZE - 1)?",":"");
  }
  fprintf(hashfp, "};\n\n");

  return 0;
}

/*===========================================================================
FUNCTION  

DESCRIPTION

DEPENDENCIES

RETURN VALUE

SIDE EFFECTS

===========================================================================*/
void write_file_header
(
FILE   *opfile_ptr
)
{

  fprintf(opfile_ptr, "/*===========================================================================\n\n");
  fprintf(opfile_ptr, "                         EDIT HISTORY FOR FILE\n\n");
  fprintf(opfile_ptr, "This section contains comments describing changes made to this file.\n");
  fprintf(opfile_ptr, "Notice that changes are listed in reverse chronological order.\n\n");
  fprintf(opfile_ptr, "   !!!!!!!!!This is an AUTO GENERATED FILE!!!!!!!!!!!!!! \n\n");
  fprintf(opfile_ptr, "============================================================================*/\n\n");
}


/*===========================================================================

FUNCTION    MAIN

DESCRIPTION
    Main program function

    Usage: pboot_hash2C input_HashFile output_CFile

DEPENDENCIES
    None.

RETURN VALUE
    !=0  Error
    0    Success

SIDE EFFECTS
    None.

===========================================================================*/
int main(int argc, char **argv)
{
  /* argv[1] = input hash file
  ** argv[2] = output C file
  */
  segments_t segment_info = {0};          /* table containing segment info */
  char *in_hash_file, *out_C_file;
  FILE *in_hash, *out_C;
  int i=0, ret;

  /* Save arguments */
  in_hash_file = argv[1];
  out_C_file = argv[2];
  OPENFILE(in_hash_file, in_hash, "rb");

  /* Generate hash table */
  OPENFILE(out_C_file, out_C, "wb+");
  write_file_header(out_C);
  ret = write_hash(in_hash, out_C);

  if ( ret )
  {
    if ( ret != ERROR ) perror("Error generating Hash C File");
    exit(-1);
  }
  printf("\n Finished writting hash C file. Closing files!\n");

  fclose(in_hash);
  fclose(out_C);
  exit(0);
}

