#ifndef CAMERA_PARMS_API_H
#define CAMERA_PARMS_API_H
/*============================================================================
  
                 Camera Service Interface Header File
  
   DESCRIPTION
     This file contains the definitions needed for the camera service
     interface.
  
============================================================================*/

/*============================================================================
 
                      EDIT HISTORY FOR FILE

 This section contains comments describing changes made to this file.
 Notice that changes are listed in reverse chronological order.

 $Header: //source/qcom/qct/multimedia/camera/6k/cameraparms/main/latest/inc/camera_parms_api.h#4 $ $DateTime: 2008/08/01 03:49:22 $ $Author: shilpam $

 when      who    what, where, why   
 --------  -----  ----------------------------------------------------------
 06/18/07  jpg     Added flags to allow exclusion of parameters such as large 
                   tables from different I/O paths (target UI, remote/PC UI, 
                   .ini file, JPEG header).
 05/24/07  klee    Added more APIs based on AEC outdoor enhancement
                   CAMERA_API_AEC_OUTDOOR_BRIGHT_ENABLE
                   CAMERA_API_AEC_OUTDOOR_BRIGHT_REDUCTION
                   CAMERA_API_AEC_OUTDOOR_BRIGHT_THRESHOLD_LO
                   CAMERA_API_AEC_OUTDOOR_BRIGHT_THRESHOLD_HI
                   CAMERA_API_AEC_OUTDOOR_BRIGHT_DISCARDED - Read only
 05/10/07  klee    Added moer APIs based on system team's request
                   CAMERA_API_AWB_SNAPSHOT_R_GAIN - Read only
                   CAMERA_API_AWB_SNAPSHOT_B_GAIN - Read only
 02/16/07  klee    Updated APIs based on system's request
 02/15/07  klee    Added more APIs
                   AWB_PREV_R_GAIN - Read only
                   AWB_PREV_B_GAIN - Read only
                   AFR_PREVIEW_FPS - Read only
                   AEC_HIGH_LUMA_REGION_THRESHOLD - Read/Write
 11/20/06  jv      Removed static saturated color conversion matrix.
 09/21/06  jn      Added AF related params.
 09/15/06  klee    Fixed crash problem with QMobiCat engine
 09/15/06  klee    Cleaned up the lint errors
 09/15/06  klee    Added implementation for AWB, AEC and ASF
 08/28/06  klee    Added implementation for the variables on 3a live screen
 08/26/06  klee    Initial Release.

============================================================================*/

/*============================================================================
                        INCLUDE FILES
============================================================================*/
#include "customer.h"
#include "comdef.h"
#ifdef FEATURE_CAMERA
#ifdef FEATURE_CAMERA_MOBICAT_CAMERA_CONFIG_H
#include "camsensor.h"
#include "camera_3a_shared.h"
#include "jpege.h"

/*============================================================================
                        EXTERNAL ABSTRACT DATA TYPES
============================================================================*/
typedef enum
{
  CAMERA_PARMS_API_READ_ONLY         = 1,
  CAMERA_PARMS_API_REQUIRES_APPLY    = 2,
  CAMERA_PARMS_API_EXCLUDE_TARGET_UI = 4,
  CAMERA_PARMS_API_EXCLUDE_REMOTE_UI = 8,
  CAMERA_PARMS_API_EXCLUDE_INI       = 16,
  CAMERA_PARMS_API_EXCLUDE_JPEG      = 32,
  CAMERA_PARMS_API_CHROMATIX         = 64
} camera_parm_api_flag_type;

typedef enum
{
#ifndef FEATURE_CAMERA_YCBCR_ONLY
  CAMERA_API_FIRST = 0,
/*************** color matrix parameters ******************/
  CAMERA_API_COLOR_CORRECTION_DEFAULT_A11 = CAMERA_API_FIRST,
  CAMERA_API_COLOR_CORRECTION_DEFAULT_A12,
  CAMERA_API_COLOR_CORRECTION_DEFAULT_A13,
  CAMERA_API_COLOR_CORRECTION_DEFAULT_A21,
  CAMERA_API_COLOR_CORRECTION_DEFAULT_A22,
  CAMERA_API_COLOR_CORRECTION_DEFAULT_A23,
  CAMERA_API_COLOR_CORRECTION_DEFAULT_A31,
  CAMERA_API_COLOR_CORRECTION_DEFAULT_A32,
  CAMERA_API_COLOR_CORRECTION_DEFAULT_A33,
  CAMERA_API_COLOR_CORRECTION_DEFAULT_BIAS_R,
  CAMERA_API_COLOR_CORRECTION_DEFAULT_BIAS_G,
  CAMERA_API_COLOR_CORRECTION_DEFAULT_BIAS_B,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_ENABLE,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_A11,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_A12,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_A13,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_A21,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_A22,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_A23,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_A31,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_A32,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_A33,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_BIAS_R,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_BIAS_G,
  CAMERA_API_COLOR_CORRECTION_LOW_LIGHT_BIAS_B,
  CAMERA_API_COLOR_CONVERSION_TL84_A11,
  CAMERA_API_COLOR_CONVERSION_TL84_A12,
  CAMERA_API_COLOR_CONVERSION_TL84_A13,
  CAMERA_API_COLOR_CONVERSION_TL84_A21,
  CAMERA_API_COLOR_CONVERSION_TL84_A22,
  CAMERA_API_COLOR_CONVERSION_TL84_A23,
  CAMERA_API_COLOR_CONVERSION_TL84_A31,
  CAMERA_API_COLOR_CONVERSION_TL84_A32,
  CAMERA_API_COLOR_CONVERSION_TL84_A33,
  CAMERA_API_COLOR_CONVERSION_TL84_BIAS_Y,
  CAMERA_API_COLOR_CONVERSION_TL84_BIAS_CB,
  CAMERA_API_COLOR_CONVERSION_TL84_BIAS_CR,
  CAMERA_API_COLOR_CONVERSION_A_A11,
  CAMERA_API_COLOR_CONVERSION_A_A12,
  CAMERA_API_COLOR_CONVERSION_A_A13,
  CAMERA_API_COLOR_CONVERSION_A_A21,
  CAMERA_API_COLOR_CONVERSION_A_A22,
  CAMERA_API_COLOR_CONVERSION_A_A23,
  CAMERA_API_COLOR_CONVERSION_A_A31,
  CAMERA_API_COLOR_CONVERSION_A_A32,
  CAMERA_API_COLOR_CONVERSION_A_A33,
  CAMERA_API_COLOR_CONVERSION_A_BIAS_Y,
  CAMERA_API_COLOR_CONVERSION_A_BIAS_CB,
  CAMERA_API_COLOR_CONVERSION_A_BIAS_CR,
  CAMERA_API_COLOR_CONVERSION_D65_A11,
  CAMERA_API_COLOR_CONVERSION_D65_A12,
  CAMERA_API_COLOR_CONVERSION_D65_A13,
  CAMERA_API_COLOR_CONVERSION_D65_A21,
  CAMERA_API_COLOR_CONVERSION_D65_A22,
  CAMERA_API_COLOR_CONVERSION_D65_A23,
  CAMERA_API_COLOR_CONVERSION_D65_A31,
  CAMERA_API_COLOR_CONVERSION_D65_A32,
  CAMERA_API_COLOR_CONVERSION_D65_A33,
  CAMERA_API_COLOR_CONVERSION_D65_BIAS_Y,
  CAMERA_API_COLOR_CONVERSION_D65_BIAS_CB,
  CAMERA_API_COLOR_CONVERSION_D65_BIAS_CR,
  CAMERA_API_COLOR_CONVERSION_MONO_A11,
  CAMERA_API_COLOR_CONVERSION_MONO_A12,
  CAMERA_API_COLOR_CONVERSION_MONO_A13,
  CAMERA_API_COLOR_CONVERSION_MONO_A21,
  CAMERA_API_COLOR_CONVERSION_MONO_A22,
  CAMERA_API_COLOR_CONVERSION_MONO_A23,
  CAMERA_API_COLOR_CONVERSION_MONO_A31,
  CAMERA_API_COLOR_CONVERSION_MONO_A32,
  CAMERA_API_COLOR_CONVERSION_MONO_A33,
  CAMERA_API_COLOR_CONVERSION_MONO_BIAS_Y,
  CAMERA_API_COLOR_CONVERSION_MONO_BIAS_CB,
  CAMERA_API_COLOR_CONVERSION_MONO_BIAS_CR,
  CAMERA_API_COLOR_CONVERSION_SEPIA_A11,
  CAMERA_API_COLOR_CONVERSION_SEPIA_A12,
  CAMERA_API_COLOR_CONVERSION_SEPIA_A13,
  CAMERA_API_COLOR_CONVERSION_SEPIA_A21,
  CAMERA_API_COLOR_CONVERSION_SEPIA_A22,
  CAMERA_API_COLOR_CONVERSION_SEPIA_A23,
  CAMERA_API_COLOR_CONVERSION_SEPIA_A31,
  CAMERA_API_COLOR_CONVERSION_SEPIA_A32,
  CAMERA_API_COLOR_CONVERSION_SEPIA_A33,
  CAMERA_API_COLOR_CONVERSION_SEPIA_BIAS_Y,
  CAMERA_API_COLOR_CONVERSION_SEPIA_BIAS_CB,
  CAMERA_API_COLOR_CONVERSION_SEPIA_BIAS_CR,
  CAMERA_API_COLOR_CONVERSION_NEGATIVE_A11,
  CAMERA_API_COLOR_CONVERSION_NEGATIVE_A12,
  CAMERA_API_COLOR_CONVERSION_NEGATIVE_A13,
  CAMERA_API_COLOR_CONVERSION_NEGATIVE_A21,
  CAMERA_API_COLOR_CONVERSION_NEGATIVE_A22,
  CAMERA_API_COLOR_CONVERSION_NEGATIVE_A23,
  CAMERA_API_COLOR_CONVERSION_NEGATIVE_A31,
  CAMERA_API_COLOR_CONVERSION_NEGATIVE_A32,
  CAMERA_API_COLOR_CONVERSION_NEGATIVE_A33,
  CAMERA_API_COLOR_CONVERSION_NEGATIVE_BIAS_Y,
  CAMERA_API_COLOR_CONVERSION_NEGATIVE_BIAS_CB,
  CAMERA_API_COLOR_CONVERSION_NEGATIVE_BIAS_CR,
  CAMERA_API_BSM_COLOR_CONVERSION_SAT_FACTOR,
  CAMERA_API_BSM_COLOR_CONVERSION_SUNSET_A11,
  CAMERA_API_BSM_COLOR_CONVERSION_SUNSET_A12,
  CAMERA_API_BSM_COLOR_CONVERSION_SUNSET_A13,
  CAMERA_API_BSM_COLOR_CONVERSION_SUNSET_A21,
  CAMERA_API_BSM_COLOR_CONVERSION_SUNSET_A22,
  CAMERA_API_BSM_COLOR_CONVERSION_SUNSET_A23,
  CAMERA_API_BSM_COLOR_CONVERSION_SUNSET_A31,
  CAMERA_API_BSM_COLOR_CONVERSION_SUNSET_A32,
  CAMERA_API_BSM_COLOR_CONVERSION_SUNSET_A33,
  CAMERA_API_BSM_COLOR_CONVERSION_SUNSET_BIAS_Y,
  CAMERA_API_BSM_COLOR_CONVERSION_SUNSET_BIAS_CB,
  CAMERA_API_BSM_COLOR_CONVERSION_SUNSET_BIAS_CR,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_TL84_A11,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_TL84_A12,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_TL84_A13,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_TL84_A21,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_TL84_A22,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_TL84_A23,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_TL84_A31,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_TL84_A32,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_TL84_A33,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_TL84_BIAS_Y,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_TL84_BIAS_CB,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_TL84_BIAS_CR,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_A_A11,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_A_A12,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_A_A13,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_A_A21,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_A_A22,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_A_A23,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_A_A31,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_A_A32,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_A_A33,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_A_BIAS_Y,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_A_BIAS_CB,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_A_BIAS_CR,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_D65_A11,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_D65_A12,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_D65_A13,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_D65_A21,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_D65_A22,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_D65_A23,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_D65_A31,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_D65_A32,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_D65_A33,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_D65_BIAS_Y,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_D65_BIAS_CB,
  CAMERA_API_BSM_COLOR_CONVERSION_SKIN_D65_BIAS_CR,

/* MWB */
  CAMERA_API_MWB_FLUORESCENT_R_GAIN,
  CAMERA_API_MWB_FLUORESCENT_G_GAIN,
  CAMERA_API_MWB_FLUORESCENT_B_GAIN,
  CAMERA_API_MWB_SUNNY_R_GAIN,
  CAMERA_API_MWB_SUNNY_G_GAIN,
  CAMERA_API_MWB_SUNNY_B_GAIN,
  CAMERA_API_MWB_TUNGSTEN_R_GAIN,
  CAMERA_API_MWB_TUNGSTEN_G_GAIN,
  CAMERA_API_MWB_TUNGSTEN_B_GAIN,
  CAMERA_API_MWB_CLOUDY_R_GAIN,
  CAMERA_API_MWB_CLOUDY_G_GAIN,
  CAMERA_API_MWB_CLOUDY_B_GAIN,
  CAMERA_API_MWB_STROBE_R_GAIN,
  CAMERA_API_MWB_STROBE_G_GAIN,
  CAMERA_API_MWB_STROBE_B_GAIN,
  CAMERA_API_MWB_LED_R_GAIN,
  CAMERA_API_MWB_LED_G_GAIN,
  CAMERA_API_MWB_LED_B_GAIN,

/*************** AWB parameters *****************/
  CAMERA_API_AWB_ENABLE,
  CAMERA_API_AWB_CHANNEL_GAIN_GREEN_EVEN_ROW,
  CAMERA_API_AWB_CHANNEL_GAIN_GREEN_ODD_ROW,
  CAMERA_API_AWB_CHANNEL_GAIN_RED,
  CAMERA_API_AWB_CHANNEL_GAIN_BLUE,
  CAMERA_API_AWB_REFERENCE_POINT_RED_D65,
  CAMERA_API_AWB_REFERENCE_POINT_BLUE_D65,
  CAMERA_API_AWB_ADJUST_GAIN_RED_D65,
  CAMERA_API_AWB_ADJUST_GAIN_BLUE_D65,
  CAMERA_API_AWB_REFERENCE_POINT_RED_D75,
  CAMERA_API_AWB_REFERENCE_POINT_BLUE_D75,
  CAMERA_API_AWB_ADJUST_GAIN_RED_D75,
  CAMERA_API_AWB_ADJUST_GAIN_BLUE_D75,
  CAMERA_API_AWB_REFERENCE_POINT_RED_A,
  CAMERA_API_AWB_REFERENCE_POINT_BLUE_A,
  CAMERA_API_AWB_ADJUST_GAIN_RED_A,
  CAMERA_API_AWB_ADJUST_GAIN_BLUE_A,
  CAMERA_API_AWB_REFERENCE_POINT_RED_TL84,
  CAMERA_API_AWB_REFERENCE_POINT_BLUE_TL84,
  CAMERA_API_AWB_ADJUST_GAIN_RED_TL84,
  CAMERA_API_AWB_ADJUST_GAIN_BLUE_TL84,
  CAMERA_API_AWB_REFERENCE_POINT_RED_CW,
  CAMERA_API_AWB_REFERENCE_POINT_BLUE_CW,
  CAMERA_API_AWB_ADJUST_GAIN_RED_CW,
  CAMERA_API_AWB_ADJUST_GAIN_BLUE_CW,
  CAMERA_API_AWB_REFERENCE_POINT_RED_H,
  CAMERA_API_AWB_REFERENCE_POINT_BLUE_H,
  CAMERA_API_AWB_ADJUST_GAIN_RED_H,
  CAMERA_API_AWB_ADJUST_GAIN_BLUE_H,
  CAMERA_API_AWB_REFERENCE_POINT_RED_D50,
  CAMERA_API_AWB_REFERENCE_POINT_BLUE_D50,
  CAMERA_API_AWB_ADJUST_GAIN_RED_D50,
  CAMERA_API_AWB_ADJUST_GAIN_BLUE_D50,
  CAMERA_API_AWB_REFERENCE_POINT_RED_CUST_F,  
  CAMERA_API_AWB_REFERENCE_POINT_BLUE_CUST_F,  
  CAMERA_API_AWB_ADJUST_GAIN_RED_CUST_F,  
  CAMERA_API_AWB_ADJUST_GAIN_BLUE_CUST_F,
  CAMERA_API_AWB_REFERENCE_POINT_RED_NOON,  
  CAMERA_API_AWB_REFERENCE_POINT_BLUE_NOON,  
  CAMERA_API_AWB_ADJUST_GAIN_RED_NOON,  
  CAMERA_API_AWB_ADJUST_GAIN_BLUE_NOON,
  CAMERA_API_AWB_LOW_LIGHT_VFE_MIN_Y,
  CAMERA_API_AWB_LOW_LIGHT_VFE_MAX_Y,
  CAMERA_API_AWB_LOW_LIGHT_VFE_M1,
  CAMERA_API_AWB_LOW_LIGHT_VFE_M2,
  CAMERA_API_AWB_LOW_LIGHT_VFE_M3,
  CAMERA_API_AWB_LOW_LIGHT_VFE_M4,
  CAMERA_API_AWB_LOW_LIGHT_VFE_C1,
  CAMERA_API_AWB_LOW_LIGHT_VFE_C2,
  CAMERA_API_AWB_LOW_LIGHT_VFE_C3,
  CAMERA_API_AWB_LOW_LIGHT_VFE_C4,
  CAMERA_API_AWB_NORMAL_LIGHT_VFE_MIN_Y,
  CAMERA_API_AWB_NORMAL_LIGHT_VFE_MAX_Y,
  CAMERA_API_AWB_NORMAL_LIGHT_VFE_M1,
  CAMERA_API_AWB_NORMAL_LIGHT_VFE_M2,
  CAMERA_API_AWB_NORMAL_LIGHT_VFE_M3,
  CAMERA_API_AWB_NORMAL_LIGHT_VFE_M4,
  CAMERA_API_AWB_NORMAL_LIGHT_VFE_C1,
  CAMERA_API_AWB_NORMAL_LIGHT_VFE_C2,
  CAMERA_API_AWB_NORMAL_LIGHT_VFE_C3,
  CAMERA_API_AWB_NORMAL_LIGHT_VFE_C4,
  CAMERA_API_AWB_OUTDOOR_VFE_MIN_Y,
  CAMERA_API_AWB_OUTDOOR_VFE_MAX_Y,
  CAMERA_API_AWB_OUTDOOR_VFE_M1,
  CAMERA_API_AWB_OUTDOOR_VFE_M2,
  CAMERA_API_AWB_OUTDOOR_VFE_M3,
  CAMERA_API_AWB_OUTDOOR_VFE_M4,
  CAMERA_API_AWB_OUTDOOR_VFE_C1,
  CAMERA_API_AWB_OUTDOOR_VFE_C2,
  CAMERA_API_AWB_OUTDOOR_VFE_C3,
  CAMERA_API_AWB_OUTDOOR_VFE_C4,
  CAMERA_API_AWB_INDOOR_INDEX,
  CAMERA_API_AWB_OUTDOOR_INDEX,
  CAMERA_API_AWB_SNOW_BLUE_ADJ_RATIO,
  CAMERA_API_AWB_BEACH_BLUE_ADJ_RATIO,
  CAMERA_API_AWB_OUTLIER_DISTANCE,
  CAMERA_API_AWB_GREEN_OFFSET_RG, 
  CAMERA_API_AWB_GREEN_OFFSET_BG,
  CAMERA_API_AWB_CURRENT_SAMPLE_DECISION,
  CAMERA_API_AWB_PREV_R_GAIN,
  CAMERA_API_AWB_PREV_B_GAIN,
  CAMERA_API_AWB_SNAPSHOT_R_GAIN,
  CAMERA_API_AWB_SNAPSHOT_B_GAIN,
  
/*************** AWB Extended parameters *****************/
  CAMERA_API_AWB_EXT_COMPACT_CLUSTER_R2,
  CAMERA_API_AWB_EXT_C_CLUSTER_TO_REF_SQ,
  CAMERA_API_AWB_EXT_A_CLUSTER_THRESH,
  CAMERA_API_AWB_EXT_F_CLUSTER_THRESH,
  CAMERA_API_AWB_EXT_DAY_CLUSTER_THRESH,
  CAMERA_API_AWB_EXT_OUTDOOR_G_THRESH,
  CAMERA_API_AWB_EXT_OUTDOOR_G_THR_BRT_F,
  CAMERA_API_AWB_EXT_OUTDOOR_G_THR_DARK_F,
  CAMERA_API_AWB_EXT_DAY_CLUSTER_THR_F,
  CAMERA_API_AWB_EXT_WB_ALOW_F_LINE,
  CAMERA_API_AWB_EXT_OUT_VALID_SAMPLES_THR,
  CAMERA_API_AWB_EXT_OUT_GREEN_UP_THRESH,
  CAMERA_API_AWB_EXT_RADIUS_SQUARED_THR,
  CAMERA_API_AWB_EXT_OUT_G_THRESH_BRIGHT_A,
  CAMERA_API_AWB_EXT_OUT_G_THRESH_DARK_A,
  CAMERA_API_AWB_EXT_DAY_CLUSTER_THR_A,
  CAMERA_API_AWB_EXT_CC_GLOBAL_GAIN,
  CAMERA_API_AWB_EXT_MIN_R_GAIN,
  CAMERA_API_AWB_EXT_MIN_G_GAIN,
  CAMERA_API_AWB_EXT_MIN_B_GAIN,
  CAMERA_API_AWB_EXT_MAX_R_GAIN,
  CAMERA_API_AWB_EXT_MAX_G_GAIN,
  CAMERA_API_AWB_EXT_MAX_B_GAIN,
  CAMERA_API_AWB_EXT_OUTDOOR_SAMPLE_INFLUENCE,
  CAMERA_API_AWB_EXT_INDOOR_SAMPLE_INFLUENCE,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INDOOR_D65,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_OUTDOOR_D65,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INOUTDOOR_D65,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INDOOR_D75,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_OUTDOOR_D75,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INOUTDOOR_D75,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INDOOR_A,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_OUTDOOR_A,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INOUTDOOR_A,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INDOOR_TL84,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_OUTDOOR_TL84,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INOUTDOOR_TL84,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INDOOR_CW,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_OUTDOOR_CW,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INOUTDOOR_CW,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INDOOR_H,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_OUTDOOR_H,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INOUTDOOR_H,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INDOOR_D50,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_OUTDOOR_D50,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INOUTDOOR_D50,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INDOOR_CUSTFLUO,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_OUTDOOR_CUSTFLUO,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INOUTDOOR_CUSTFLUO,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INDOOR_NOON,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_OUTDOOR_NOON,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INOUTDOOR_NOON,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INDOOR_DAYLIGHT,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_OUTDOOR_DAYLIGHT,
  CAMERA_API_AWB_EXT_WEIGHT_VECTOR_INOUTDOOR_DAYLIGHT,
  CAMERA_API_AWB_EXT_WHITE_WORLD_Y_MIN_RATIO,

  /*************** Gamma *************************/
  CAMERA_API_GAMMA_DEFAULT,
  CAMERA_API_GAMMA_LOW_LIGHT,
  CAMERA_API_GAMMA_OUTDOOR,    
  CAMERA_API_GAMMA_BACK_LIGHT, 
  CAMERA_API_GAMMA_SOLARIZED, 

  /************* Black Level**********************/
  CAMERA_API_BLACK_LEVEL_NORMAL_LIGHT_OFFSET, 
#if 0 //TODO: Updated values to be reflected in services  
  CAMERA_API_BLACK_LEVEL_LOW_LIGHT_OFFSET,
#endif  
#ifdef QDSP_MODULE_VFE25_DEFINED
#error code not present
#endif /* QDSP_MODULE_VFE25_DEFINED */
  /*************** Rolloff ************************/
#ifndef QDSP_MODULE_VFE25_DEFINED
  CAMERA_API_ROLLOFF_TABLE_TL84_CX,
  CAMERA_API_ROLLOFF_TABLE_TL84_CY,
  CAMERA_API_ROLLOFF_TABLE_TL84_WIDTH,
  CAMERA_API_ROLLOFF_TABLE_TL84_HEIGHT,
  CAMERA_API_ROLLOFF_TABLE_TL84_NUM_INTERVALS,
  CAMERA_API_ROLLOFF_TABLE_TL84_RADIUS_SQUARE_TABLE,
  CAMERA_API_ROLLOFF_TABLE_TL84_RED_CORRECTION_TABLE,
  CAMERA_API_ROLLOFF_TABLE_TL84_GREEN_CORRECTION_TABLE,
  CAMERA_API_ROLLOFF_TABLE_TL84_BLUE_CORRECTION_TABLE,
  CAMERA_API_ROLLOFF_TABLE_A_CX,
  CAMERA_API_ROLLOFF_TABLE_A_CY,
  CAMERA_API_ROLLOFF_TABLE_A_WIDTH,
  CAMERA_API_ROLLOFF_TABLE_A_HEIGHT,
  CAMERA_API_ROLLOFF_TABLE_A_NUM_INTERVALS,
  CAMERA_API_ROLLOFF_TABLE_A_RADIUS_SQUARE_TABLE,
  CAMERA_API_ROLLOFF_TABLE_A_RED_CORRECTION_TABLE,
  CAMERA_API_ROLLOFF_TABLE_A_GREEN_CORRECTION_TABLE,
  CAMERA_API_ROLLOFF_TABLE_A_BLUE_CORRECTION_TABLE,
  CAMERA_API_ROLLOFF_TABLE_D65_CX,
  CAMERA_API_ROLLOFF_TABLE_D65_CY,
  CAMERA_API_ROLLOFF_TABLE_D65_WIDTH,
  CAMERA_API_ROLLOFF_TABLE_D65_HEIGHT,
  CAMERA_API_ROLLOFF_TABLE_D65_NUM_INTERVALS,
  CAMERA_API_ROLLOFF_TABLE_D65_RADIUS_SQUARE_TABLE,
  CAMERA_API_ROLLOFF_TABLE_D65_RED_CORRECTION_TABLE,
  CAMERA_API_ROLLOFF_TABLE_D65_GREEN_CORRECTION_TABLE,
  CAMERA_API_ROLLOFF_TABLE_D65_BLUE_CORRECTION_TABLE,
  CAMERA_API_ROLLOFF_TABLE_LOW_LIGHT_CX,
  CAMERA_API_ROLLOFF_TABLE_LOW_LIGHT_CY,
  CAMERA_API_ROLLOFF_TABLE_LOW_LIGHT_WIDTH,
  CAMERA_API_ROLLOFF_TABLE_LOW_LIGHT_HEIGHT,
  CAMERA_API_ROLLOFF_TABLE_LOW_LIGHT_NUM_INTERVALS,
  CAMERA_API_ROLLOFF_TABLE_LOW_LIGHT_RADIUS_SQUARE_TABLE,
  CAMERA_API_ROLLOFF_TABLE_LOW_LIGHT_RED_CORRECTION_TABLE,
  CAMERA_API_ROLLOFF_TABLE_LOW_LIGHT_GREEN_CORRECTION_TABLE,
  CAMERA_API_ROLLOFF_TABLE_LOW_LIGHT_BLUE_CORRECTION_TABLE,
#endif /* !QDSP_MODULE_VFE25_DEFINED */
#ifdef QDSP_MODULE_VFE25_DEFINED
#error code not present
#endif /* QDSP_MODULE_VFE25_DEFINED */
  /*************** AEC parameters *****************/
  CAMERA_API_AEC_ENABLE,
  CAMERA_API_AEC_AGGRESSIVENESS,
  CAMERA_API_AEC_HIGH_LUMA_REGION_THRESHOLD,
  CAMERA_API_AEC_CURRENT_SENSOR_LUMA, // included in 3A
  CAMERA_API_AEC_CURRENT_VFE_LUMA,
  CAMERA_API_AEC_CURRENT_EXP_INDEX,
  CAMERA_API_AEC_OUTDOOR_BRIGHT_ENABLE,
  CAMERA_API_AEC_OUTDOOR_BRIGHT_REDUCTION,
  CAMERA_API_AEC_OUTDOOR_BRIGHT_THRESHOLD_LO,
  CAMERA_API_AEC_OUTDOOR_BRIGHT_THRESHOLD_HI,
  CAMERA_API_AEC_OUTDOOR_BRIGHT_DISCARDED,
#if 0 //TODO: Updated values to be reflected in services  
  CAMERA_API_AEC_EXPOSURE_GAIN_TYPE,
#endif  
  CAMERA_API_AEC_NUM_EXPOSURE_VALUES,
  CAMERA_API_AEC_TABLE_EXPOSURE_ENTRIES_GAIN,
  CAMERA_API_AEC_TABLE_EXPOSURE_ENTRIES_LINE_CT,
  CAMERA_API_AEC_LUMA_TARGET_DEFAULT,
  CAMERA_API_AEC_LUMA_TARGET_OUTDOOR,
  CAMERA_API_AEC_LUMA_TARGET_LOW_LIGHT,
  CAMERA_API_AEC_LUMA_TARGET_BACK_LIGHT,
  CAMERA_API_AEC_TOLERANCE,
  CAMERA_API_AEC_EXP_INDEX_ADJ_STEP,
  CAMERA_API_AEC_ISO100_GAIN,
  CAMERA_API_AEC_INDOOR_INDEX,
  CAMERA_API_AEC_OUTDOOR_INDEX,
/*************** 3x3 luma filter ***************/
  CAMERA_API_3X3_LUMA_ENABLE,
  CAMERA_API_3X3_LUMA_HW_OR_SW,

  /*************** 3x3 h/w ASF parameters ******************/
  CAMERA_API_3X3_ASF_ENABLE,
#ifndef QDSP_MODULE_VFE25_DEFINED
  CAMERA_API_3X3_ASF_EDGE_FILTER,
  CAMERA_API_3X3_ASF_NOISE_FILTER,
  CAMERA_API_3X3_ASF_E_THRESHOLD,
  CAMERA_API_3X3_ASF_N_THRESHOLD,
  CAMERA_API_3X3_ASF_E_DETECTION_FLAG,
#endif /* !QDSP_MODULE_VFE25_DEFINED */
#if 0 //TODO: Updated values to be reflected in services  
  CAMERA_API_3X3_ASF_LOW_LIGHT_EDGE_FILTER,
  CAMERA_API_3X3_ASF_LOW_LIGHT_NOISE_FILTER,
  CAMERA_API_3X3_ASF_LOW_LIGHT_E_THRESHOLD,
  CAMERA_API_3X3_ASF_LOW_LIGHT_N_THRESHOLD,
  CAMERA_API_3X3_ASF_LOW_LIGHT_E_DETECTION_FLAG,
#endif
#ifdef QDSP_MODULE_VFE25_DEFINED
#error code not present
#endif /* QDSP_MODULE_VFE25_DEFINED */
  /*************** luma adaptation ***************/
  CAMERA_API_LUMA_ADAP_ENABLE, 
  CAMERA_API_LUMA_ADAP_THRESHOLD, 

  /*************** chroma suppression ************/
  CAMERA_API_CHRO_SUP_ENABLE, 
  CAMERA_API_CHRO_SUP_LUMA_THRES_1, 
  CAMERA_API_CHRO_SUP_LUMA_THRES_2, 
  CAMERA_API_CHRO_SUP_LUMA_THRES_3, 
  CAMERA_API_CHRO_SUP_LUMA_THRES_4, 
  CAMERA_API_CHRO_SUP_CHRO_THRES_1, 
  CAMERA_API_CHRO_SUP_CHRO_THRES_2, 

  /*************** HJR ***************************/
  CAMERA_API_HJR_ENABLE, 
  CAMERA_API_HJR_MAX_NUM_FRAMES, 
  CAMERA_API_HJR_ONE_TO_TWO_OFFSET, 
  CAMERA_API_HJR_N_REDUCTION_FLAT, 
  CAMERA_API_HJR_N_REDUCTION_TEXTURE, 
  CAMERA_API_HJR_TEXTURE_THRESHOLD, 
  CAMERA_API_HJR_K_TABLE,
  CAMERA_API_HJR_BAYER_FILTERING_ENABLE,
#ifdef QDSP_MODULE_VFE25_DEFINED
#error code not present
#endif /* QDSP_MODULE_VFE25_DEFINED */
  /**************Auto Flicker Detection************/
 #if 0 //TODO: Updated values to be reflected in services
  CAMERA_API_AFD_DETECTION_DATA_STD_THRESH,
  CAMERA_API_AFD_DETECTION_DATA_PCT_THRESH,
  CAMERA_API_AFD_DETECTION_DATA_DIFF_THRESH,
  CAMERA_API_AFD_DETECTION_DATA_FRAME_CT_THRESH,
#endif
  /***************BPC- Bad/Defect pixel correction ********/
  CAMERA_API_DEFECT_PIXEL_COR_ENABLE,
  CAMERA_API_DEFECT_PIXEL_COR_THRESHOLD_MIN,
  CAMERA_API_DEFECT_PIXEL_COR_THRESHOLD_MAX,
#ifdef QDSP_MODULE_VFE25_DEFINED
#error code not present
#endif /* QDSP_MODULE_VFE25_DEFINED */
  /*************** Anti-baidng parameters *********/
  CAMERA_API_ANTI_BAND_ENABLE,
  CAMERA_API_ANTI_BAND_PIXEL_CLK,
  CAMERA_API_ANTI_BAND_PIXEL_CLK_PER_LINE,

  /*************** AFR parameters *****************/
  CAMERA_API_AFR_ENABLE,
  CAMERA_API_AFR_POSSIBLE_FRAME_COUNT,
  CAMERA_API_AFR_PREVIEW_FPS,
  
#endif /* nFEATURE_CAMERA_YCBCR_ONLY */
 
  /*************** AF parameters ******************/
  CAMERA_API_AF_ENABLE,
  CAMERA_API_AF_GROSS_STEP,
  CAMERA_API_AF_FINE_STEP,
  CAMERA_API_AF_FINE_SEARCH_POINTS,
  CAMERA_API_AF_PROCESS,
  CAMERA_API_AF_MODE,
  CAMERA_API_AF_NEAR_END,
  CAMERA_API_AF_BOUNDARY,
  CAMERA_API_AF_FAR_END,
  CAMERA_API_AF_COLLECT_END_STAT,
  CAMERA_API_AF_TEST_MODE,
  CAMERA_API_AF_UNDERSHOOT_PROTECT,
  CAMERA_API_AF_RESET_LENS_AFTER_SNAP,
  CAMERA_API_AF_CLIP_TO_AF_RATIO,
  CAMERA_API_AF_WINDOW_MAX_Y,
  CAMERA_API_AF_WINDOW_MIN_Y,
  CAMERA_API_AF_POSITION,
  CAMERA_API_AF_TRACE_POSITIONS,
  CAMERA_API_AF_TRACE_STATS,
  CAMERA_API_AF_TRACE_FOCUS_TIME,
  CAMERA_API_AF_WINDOW_LAST_LINE,
  CAMERA_API_AF_WINDOW_1ST_LINE,
  CAMERA_API_AF_WINDOW_LAST_PIXEL,
  CAMERA_API_AF_WINDOW_1ST_PIXEL,
 
  /*************** signals end of enumeration *****/
  CAMERA_API_LAST 
} camera_api_parms_type;

#ifndef  FEATURE_CAMERA_MOBICAT
typedef enum 
{
  JPEGENC_MC_UINT8  = 0,
  JPEGENC_MC_INT8   = 1,
  JPEGENC_MC_UINT16 = 2,
  JPEGENC_MC_INT16  = 3,
  JPEGENC_MC_UINT32 = 4,
  JPEGENC_MC_INT32  = 5,
  JPEGENC_MC_FLOAT  = 6,
  JPEGENC_MC_DOUBLE = 7
} JPEGENC_mc_type;
#endif /* nFEATURE_CAMERA_MOBICAT */

typedef struct
{
  /* Display name of the parameter */
  char            *name;

  /* Data type for the presentation,
   * writing to .ini files and JPEG headers.
   */
  JPEGENC_mc_type parm_type;

  /* If not a table, num_elements is set to 1. */
  int32          num_elements;

  /* Points to a variable of parm_type containing the lowest value allowed.  
   * If null, type’s lowest value is used.
   */
  void            *min;

  /* Points to a variable of parm_type containing the highest value allowed.  
   * If null, type’s highest value is used.
   */
  void            *max;

  /* Parameter should be displayed as a set of strings.  
   * For instance, aec mode values may be 
   * { frame average, center weighted, spot metering}.  
   * In this case, camera services would fill in this structure with pointers 
   * to values JPEGENC_MC_UINT8 for parm_type, 0 for min, 2 for max, 
   * and the table of these strings for value_name. 
   */
  char            **value_names;

  /* Increment points to a variable of  parm_type containing the amount the 
   * parameter should be incremented or decremented when the user presses the 
   * up or down keys.  If null, the default increment of 1 for integers or 
   * 0.1 for floats will be used.
   */
  void            *increment;

  /* Flags is a bit field to indicate other information about the parameter.  
   * The following values are defined: 
   * CAMERA_PARMS_API_READ_ONLY = 1,
   * CAMERA_PARMS_API_REQUIRES_APPLY
   */
  camera_parm_api_flag_type          flags;
} camera_tune_parm_format_type;

/* The following enumeration is defined and designates whether 
 * QMobiCaT is calling the API during init phase or run phase:
 */
typedef enum
{
  CAMERA_TUNE_PHASE_INIT = 0,
  CAMERA_TUNE_PHASE_RUN
} camera_tune_phase_type;


/*============================================================================
                        API DECLARATIONS
============================================================================*/

/*===========================================================================

FUNCTION      CAMERA_PARMS_INIT

DESCRIPTION
  to initialize API.

CALLER
  camera_tune_init().

RETURN VALUE

===========================================================================*/
camera_ret_code_type camera_parms_init (void);

/*===========================================================================

FUNCTION      CAMERA_PARMS_READ

DESCRIPTION
  This API reads a parameter value and format.
  phase [in]      : Phase when parameter is being read.
  parm  [in]      : Enumerated value specifying the parameter to be read.
  table_index [in]: If parameter is a table
                    if >= 0, only the corresponding element of the table is read.
                    if -1 the whole table is read.
  value [out]     : Pointer to (type)value. Camera services allocates and frees this, if necessary.
  format [out]    : Structure specifying parameter format.

RETURN VALUE

===========================================================================*/
camera_ret_code_type camera_parms_read (
  camera_tune_phase_type        phase, 
  camera_api_parms_type         parm,
  /* If table_index is >= 0, 
   * only the corresponding member of the table is affected.  
   * If table_index is -1, the API operates on the entire table.
   */
  int32                         table_index, 
  void                          **value,
  camera_tune_parm_format_type  *format
);

/*===========================================================================

FUNCTION      CAMERA_PARMS_WRITE

DESCRIPTION
  This API writes a parameter value. Camera services applies the value written.
  phase [in]      : Phase when parameter is being written.
  parm  [in]      : Enumerated value specifying the parameter to be written.
  table_index [in]: If parameter is a table
                   if >= 0, only the corresponding element of the table is written.
                   if -1 the whole table is written.
 value [in]      : Pointer to (type)value. 

RETURN VALUE

===========================================================================*/
camera_ret_code_type camera_parms_write (
  camera_tune_phase_type     phase, 
  camera_api_parms_type      parm, 
  /* If table_index is >= 0, 
   * only the corresponding member of the table is affected.  
   * If table_index is -1, the API operates on the entire table.
   */
  int32                      table_index,
  const void                 *value
);

/*===========================================================================

FUNCTION      CAMERA_PARMS_APPLY

DESCRIPTION
  This API applies changes that are better done after all changes are made
  instead of after each individual change.

RETURN VALUE

===========================================================================*/
camera_ret_code_type camera_parms_apply ( void );

#endif /* FEATURE_CAMERA_MOBICAT_CAMERA_CONFIG_H */
#endif /* FEATURE_CAMERA */
#endif /* CAMERA_PARMS_API_H */

