#ifndef SETTINGSDIAG_H
#define SETTINGSDIAG_H

/*============================================================================
   Subsystem command code
============================================================================*/

#define APPS_SUBSYS_SETTINGS_CMD 0x0005

/*============================================================================
   Enumerated types for Settings diag
============================================================================*/

/*
    Enumerated type defining available application command codes for display
*/

typedef enum
{
  SETTINGSDIAG_START = 0,
  SETTINGSDIAG_END,
  SETTINGSDIAG_DISPLAY_START,
  SETTINGSDIAG_DISPLAY_END,
  SETTINGSDIAG_DISPLAY_BACKLIGHT_DURATION_MENU_HOME,
//5
  SETTINGSDIAG_DISPLAY_BACKLIGHT_DURATION_ALWAYS_ON,
  SETTINGSDIAG_DISPLAY_BACKLIGHT_DURATION_10_SEC,
  SETTINGSDIAG_DISPLAY_BACKLIGHT_DURATION_30_SEC,
  SETTINGSDIAG_DISPLAY_BACKLIGHT_DURATION_ALWAYS_OFF,
  SETTINGSDIAG_DISPLAY_AUTO_HYPHEN_ON,
//10
  SETTINGSDIAG_DISPLAY_AUTO_HYPHEN_OFF,
  SETTINGSDIAG_EXTRAS_START,
  SETTINGSDIAG_EXTRAS_END,
  SETTINGSDIAG_EXTRAS_SIO_DSBAUD_MENU_HOME,
  SETTINGSDIAG_EXTRAS_SIO_DSBAUD_AUTOBAUD,
//15
  SETTINGSDIAG_EXTRAS_SIO_DSBAUD_9600,
  SETTINGSDIAG_EXTRAS_SIO_DSBAUD_19200,
  SETTINGSDIAG_EXTRAS_SIO_DSBAUD_38400,
  SETTINGSDIAG_EXTRAS_SIO_DSBAUD_57600,
  SETTINGSDIAG_EXTRAS_SIO_DSBAUD_115200,
//20
  SETTINGSDIAG_EXTRAS_SIO_DSBAUD_239400,
  SETTINGSDIAG_EXTRAS_SIO_DSBAUD_460800,
  SETTINGSDIAG_EXTRAS_AUTO_ANSWER_ON,
  SETTINGSDIAG_EXTRAS_AUTO_ANSWER_OFF,
  SETTINGSDIAG_EXTRAS_AUTO_RETRY_MENU_HOME,
//25
  SETTINGSDIAG_EXTRAS_AUTO_RETRY_OFF,
  SETTINGSDIAG_EXTRAS_AUTO_RETRY_10SEC,
  SETTINGSDIAG_EXTRAS_AUTO_RETRY_30SEC,
  SETTINGSDIAG_EXTRAS_AUTO_RETRY_60SEC,
  SETTINGSDIAG_EXTRAS_ONE_TOUCH_ON,
//30
  SETTINGSDIAG_EXTRAS_ONE_TOUCH_OFF,
  SETTINGSDIAG_EXTRAS_PRIVACY_STANDARD,
  SETTINGSDIAG_EXTRAS_PRIVACY_ENHANCED,
  SETTINGSDIAG_KEYGAURD_START,
  SETTINGSDIAG_KEYGAURD_END,
//35
  SETTINGSDIAG_KEYGAURD_GAURD_NEW,
  SETTINGSDIAG_KEYGAURD_15S_AUTOGAURD,
  SETTINGSDIAG_KEYGAURD_30S_AUTOGAURD,
  SETTINGSDIAG_KEYGAURD_1M_AUTOGAURD,
  SETTINGSDIAG_NETWORK_START,
//40
  SETTINGSDIAG_NETWORK_END,
  SETTINGSDIAG_NETWORK_MODE_PREF_MENU_HOME,
  SETTINGSDIAG_NETWORK_MODE_PERF_AUTOMATIC,
  SETTINGSDIAG_NETWORK_MODE_PERF_AMPS_ONLY,
  SETTINGSDIAG_NETWORK_MODE_PERF_HDR_ONLY,
//45 
  SETTINGSDIAG_NETWORK_MODE_PERF_CDMA_AMPS,
  SETTINGSDIAG_NETWORK_MODE_PERF_CDMA_ONLY,
  SETTINGSDIAG_NETWORK_MODE_PERF_EMERGENCY_CALLS_ONLY,
  SETTINGSDIAG_NETWORK_MODE_PERF_GSM_ONLY,
  SETTINGSDIAG_NETWORK_MODE_PERF_DIGITAL_ONLY,
//50
  SETTINGSDIAG_NETWORK_MODE_PERF_WCDMA_ONLY,
  SETTINGSDIAG_NETWORK_ROAM_PREF_MENU_HOME,
  SETTINGSDIAG_NETWORK_ROAM_PREF_ANY,
  SETTINGSDIAG_NETWORK_ROAM_PREF_HOME_ONLY,
  SETTINGSDIAG_NETWORK_ROAM_PREF_AFFILIATED,
//55  
  SETTINGSDIAG_NETWORK_NW_SEL_PREF_MENU_HOME,
  SETTINGSDIAG_NETWORK_NW_SEL_PREF_AUTOMATIC,
  SETTINGSDIAG_NETWORK_NW_SEL_PREF_MANUAL,
  SETTINGSDIAG_NETWORK_NW_SEL_PREF_LIMITED_SERVICE,
  SETTINGSDIAG_MAX_CMD,

  SETTINGSDIAG_FORCE_4_BYTES = 0x10000000
} SETTINGSDIAG_CommandsType;


/*============================================================================

PACKET   SETTINGSDIAG_CMD

PURPOSE  Sent from the DM to the DMSS to issue a particular Mobimon command.

RESPONSE The DM sends back an settingsdiag_cmd_rsp_type packet to give the 
         status of the request.

============================================================================*/
typedef struct
{
  diagpkt_subsys_header_type header;

} settingsdiag_cmd_rsp_type;

#endif /*  SETTINGSDIAG_H */


