# ############################################### #
# GNU Make file for widgets
#
# Mandatory Vars to be exported from here
#	PROJECT,DIRDEPTH
# ############################################### #

# -- the target
export PROJECT=widgets
export DIRDEPTH = ..

### include generic makefile ###
include $(DIRDEPTH)/ext.mak
