/*============================================================================
                CAMERA BESTSHOT CONFIG
   DESCRIPTION
    Table defining bestshot modes. Entries in this table must match those 
    listed in camera_bestshot_mode_type defined in camera.h

   Copyright (c) 2006 by QUALCOMM, Incorporated.  All Rights Reserved.
============================================================================*/

/*============================================================================

                      EDIT HISTORY FOR FILE

 This section contains comments describing changes made to this file.
 Notice that changes are listed in reverse chronological order.

 $Header: //source/qcom/qct/multimedia/camera/6k/3a/common/main/latest/inc/camera_bestshot_config.h#2 $ $DateTime: 2009/04/14 01:30:42 $ $Author: cgera $

 when      who    what, where, why
 --------  -----  ----------------------------------------------------------
 04/14/09  cg     Added support for PartyMode BestShot 
 10/26/06  jv     Added soft focus for best shot.
 10/05/06  jv     Fix CR 103447. Turn off HJR for Portrait mode.
 09/14/06  jv     Added white balance adjustment to best shot table
 08/15/06  JV     Added mode to initializers. Removed Text mode.
 07/11/06  JV     Updated types to be bestshot specific

============================================================================*/

{ /* Landscape */
  CAMERA_BESTSHOT_LANDSCAPE, 
  CAMERA_BS_GAMMA_TABLE_OUTDOOR,
  CAMERA_BS_ISO_AUTO,
  CAMERA_BS_EV_CURRENT,
  CAMERA_BS_AEC_FRAME_AVERAGE,
  CAMERA_BS_AF_MODE_INF,
  CAMERA_BS_WB_OUTDOOR_AWB,
  CAMERA_BS_COLOR_CORRECTION_NORMAL,
  CAMERA_BS_COLOR_CONVERSION_NORMAL,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SPECIAL_WB_ADJ_NONE,
  CAMERA_BS_SOFT_FOCUS_OFF
},
{ /* Snow */
  CAMERA_BESTSHOT_SNOW,
  CAMERA_BS_GAMMA_TABLE_OUTDOOR,
  CAMERA_BS_ISO_AUTO,
  CAMERA_BS_EV_HI,
  CAMERA_BS_AEC_FRAME_AVERAGE,
  CAMERA_BS_AF_MODE_NORMAL,
  CAMERA_BS_WB_OUTDOOR_AWB,
  CAMERA_BS_COLOR_CORRECTION_NORMAL,
  CAMERA_BS_COLOR_CONVERSION_NORMAL,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SPECIAL_WB_ADJ_SNOW_BLUE_GAIN,
  CAMERA_BS_SOFT_FOCUS_OFF
},
{ /* Beach */
  CAMERA_BESTSHOT_BEACH,
  CAMERA_BS_GAMMA_TABLE_OUTDOOR,
  CAMERA_BS_ISO_AUTO,
  CAMERA_BS_EV_HI,
  CAMERA_BS_AEC_FRAME_AVERAGE,
  CAMERA_BS_AF_MODE_NORMAL,
  CAMERA_BS_WB_OUTDOOR_AWB,
  CAMERA_BS_COLOR_CORRECTION_NORMAL,
  CAMERA_BS_COLOR_CONVERSION_NORMAL,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SPECIAL_WB_ADJ_BEACH_BLUE_GAIN,
  CAMERA_BS_SOFT_FOCUS_OFF
},
{ /* Sunset */
  CAMERA_BESTSHOT_SUNSET,
  CAMERA_BS_GAMMA_TABLE_NORMAL,
  CAMERA_BS_ISO_AUTO,
  CAMERA_BS_EV_LO,
  CAMERA_BS_AEC_FRAME_AVERAGE,
  CAMERA_BS_AF_MODE_INF,
  CAMERA_BS_WB_TUNGSTON,
  CAMERA_BS_COLOR_CORRECTION_NORMAL,
  CAMERA_BS_COLOR_CONVERSION_SUNSET,
  CAMERA_BS_SETTING_ON,
  CAMERA_BS_SETTING_OFF,
  CAMERA_BS_SPECIAL_WB_ADJ_NONE,
  CAMERA_BS_SOFT_FOCUS_OFF
},
{ /* Night */
  CAMERA_BESTSHOT_NIGHT,
  CAMERA_BS_GAMMA_TABLE_LOWLIGHT,
  CAMERA_BS_ISO_AUTO,
  CAMERA_BS_EV_CURRENT,
  CAMERA_BS_AEC_CENTER_WEIGHTED,
  CAMERA_BS_AF_MODE_NORMAL,
  CAMERA_BS_WB_SGW_AWB,
  CAMERA_BS_COLOR_CORRECTION_LOW_LIGHT,
  CAMERA_BS_COLOR_CONVERSION_NORMAL,
  CAMERA_BS_SETTING_ON,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SPECIAL_WB_ADJ_NONE,
  CAMERA_BS_SOFT_FOCUS_OFF
},
{ /* Portrait*/
  CAMERA_BESTSHOT_PORTRAIT,
  CAMERA_BS_GAMMA_TABLE_NORMAL,
  CAMERA_BS_ISO_AUTO,
  CAMERA_BS_EV_CURRENT,
  CAMERA_BS_AEC_CENTER_WEIGHTED,
  CAMERA_BS_AF_MODE_NORMAL,
  CAMERA_BS_WB_AUTO_OR_FLASH,
  CAMERA_BS_COLOR_CORRECTION_NORMAL,
  CAMERA_BS_COLOR_CONVERSION_SKIN_TONE,
  CAMERA_BS_SETTING_OFF,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SPECIAL_WB_ADJ_NONE,
  CAMERA_BS_SOFT_FOCUS_ON
},
{ /* Backlight */
  CAMERA_BESTSHOT_BACKLIGHT,
  CAMERA_BS_GAMMA_TABLE_BACKLIGHT,
  CAMERA_BS_ISO_AUTO,
  CAMERA_BS_EV_CURRENT,
  CAMERA_BS_AEC_CENTER_WEIGHTED,
  CAMERA_BS_AF_MODE_NORMAL,
  CAMERA_BS_WB_AUTO,
  CAMERA_BS_COLOR_CORRECTION_NORMAL,
  CAMERA_BS_COLOR_CONVERSION_NORMAL,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SETTING_ON,
  CAMERA_BS_SPECIAL_WB_ADJ_NONE,
  CAMERA_BS_SOFT_FOCUS_OFF
},
{ /* Sports */
  CAMERA_BESTSHOT_SPORTS,
  CAMERA_BS_GAMMA_TABLE_OUTDOOR,
  CAMERA_BS_ISO_400,
  CAMERA_BS_EV_CURRENT,
  CAMERA_BS_AEC_CENTER_WEIGHTED,
  CAMERA_BS_AF_MODE_INF,
  CAMERA_BS_WB_OUTDOOR_AWB,
  CAMERA_BS_COLOR_CORRECTION_NORMAL,
  CAMERA_BS_COLOR_CONVERSION_NORMAL,
  CAMERA_BS_SETTING_OFF,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SPECIAL_WB_ADJ_NONE,
  CAMERA_BS_SOFT_FOCUS_OFF
},
{ /* AntiShake */
  CAMERA_BESTSHOT_ANTISHAKE,
  CAMERA_BS_GAMMA_TABLE_NORMAL,
  CAMERA_BS_ISO_AUTO,
  CAMERA_BS_EV_CURRENT,
  CAMERA_BS_AEC_CENTER_WEIGHTED,
  CAMERA_BS_AF_MODE_NORMAL,
  CAMERA_BS_WB_AUTO,
  CAMERA_BS_COLOR_CORRECTION_NORMAL,
  CAMERA_BS_COLOR_CONVERSION_NORMAL,
  CAMERA_BS_SETTING_ON,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SPECIAL_WB_ADJ_NONE,
  CAMERA_BS_SOFT_FOCUS_OFF
},
{ /* Flowers */
  CAMERA_BESTSHOT_FLOWERS,
  CAMERA_BS_GAMMA_TABLE_NORMAL,
  CAMERA_BS_ISO_AUTO,
  CAMERA_BS_EV_CURRENT,
  CAMERA_BS_AEC_CENTER_WEIGHTED,
  CAMERA_BS_AF_MODE_MACRO,
  CAMERA_BS_WB_AUTO,
  CAMERA_BS_COLOR_CORRECTION_NORMAL,
  CAMERA_BS_COLOR_CONVERSION_SATURATED,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SETTING_OFF,
  CAMERA_BS_SPECIAL_WB_ADJ_NONE,
  CAMERA_BS_SOFT_FOCUS_OFF
},
{ /* Candle Light */
  CAMERA_BESTSHOT_CANDLELIGHT,
  CAMERA_BS_GAMMA_TABLE_NORMAL,
  CAMERA_BS_ISO_AUTO,
  CAMERA_BS_EV_LO,
  CAMERA_BS_AEC_CENTER_WEIGHTED,
  CAMERA_BS_AF_MODE_NORMAL,
  CAMERA_BS_WB_TUNGSTON,
  CAMERA_BS_COLOR_CORRECTION_NORMAL,
  CAMERA_BS_COLOR_CONVERSION_SUNSET,
  CAMERA_BS_SETTING_ON,
  CAMERA_BS_SETTING_OFF,
  CAMERA_BS_SPECIAL_WB_ADJ_NONE,
  CAMERA_BS_SOFT_FOCUS_OFF
},
{ /* Party Mode */
  CAMERA_BESTSHOT_PARTY,
  CAMERA_BS_GAMMA_TABLE_NORMAL,
  CAMERA_BS_ISO_AUTO,
  CAMERA_BS_EV_CURRENT,
  CAMERA_BS_AEC_CENTER_WEIGHTED,
  CAMERA_BS_AF_MODE_NORMAL,
  CAMERA_BS_WB_INDOOR_AWB,
  CAMERA_BS_COLOR_CORRECTION_NORMAL,
  CAMERA_BS_COLOR_CONVERSION_SATURATED,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SETTING_CURRENT,
  CAMERA_BS_SPECIAL_WB_ADJ_NONE,
  CAMERA_BS_SOFT_FOCUS_OFF
}
