#ifndef	A8_USBDSCR_H
#define	A8_USBDSCR_H
#include	"A8_common.h"
extern	u_char DEVICE_QUALIFIER_DESCRIPTOR_DATA1[0x0A];
extern	u_char HS_CONFIG_DESCRIPTOR_DATA1[0x20];
extern	u_char DEVICE_DESCRIPTOR_DATA1[0x12];
extern	u_char CONFIG_DESCRIPTOR_DATA1[0x20];
extern	u_char DEVICE_QUALIFIER_DESCRIPTOR_DATA2[0x0A];
extern	u_char DEVICE_DESCRIPTOR_DATA2[0x12];
extern	u_char CONFIG_DESCRIPTOR_DATA2[0x20];
extern	u_char LANGUAGE_ID_DATA[0x04];
extern	u_char MANUFACTURER_STRING_DATA[0x1E];
extern	u_char PRODUCT_STRING_DATA[0x1E];
extern	u_char SERIALNUMBER_STRING_DATA[0x1a];
extern	u_char MODE_SENSE_TABLE_START[0x08];


extern	u_char DEVICE_QUALIFIER_DESCRIPTOR_DATA5[0x0A];
extern	u_char HS_CONFIG_DESCRIPTOR_DATA5[0x43];
extern	u_char DEVICE_DESCRIPTOR_DATA5[0x12];
extern	u_char CONFIG_DESCRIPTOR_DATA5[0x43];



extern	u_char REQUEST_SENSE_TABLE1_START[0x12];
extern	u_char REQUEST_SENSE_TABLE2_START[0x0E];
extern	u_char MODE_SENSE_TABLE00_START[0x02];
extern	u_char MODE_SENSE_TABLE1C_START[0x0C];
extern	u_char  MODE_SENSE_TABLE3F_START[0x44];
#endif


