/*=============================================================================
   PROGRESSIVE  BOOT ELF PROGRAM HEADER  FLAGS  MODIFICATION  TOOL

   This program takes in an ELF file, a scatter load file and
   modifies the ELF file Program Header Flags to the one specified in the
   Scatter loader

EXTERNALIZED FUNCTIONS

INITIALIZATION AND SEQUENCING REQUIREMENTS

Copyright (c) 2005, 2006 by QUALCOMM, Inc.  All Rights Reserved.
=============================================================================*/

/*=============================================================================

                            EDIT HISTORY FOR MODULE

  This section contains comments describing changes made to the module.
  Notice that changes are listed in reverse chronological order.

  $Header: //depot/asic/msmshared/tools/pboot/modify_elf_flags.c#2 $

when       who     what, where, why
--------   ---     ------------------------------------------------------------
08/31/06   rjain   Ported from 6800b for Simple elf support
07/14/06   tk      Created

=============================================================================*/


/*=============================================================================

                            INCLUDE FILES FOR MODULE

=============================================================================*/
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/types.h>
#include <unistd.h>
#include <string.h>
#include <stdint.h>
#include "pboot_elf_utils.h"

/*=============================================================================

            LOCAL DEFINITIONS AND DECLARATIONS FOR MODULE

=============================================================================*/

bool debug_print = 0;            /* global debug option */

/*=============================================================================

                              FUNCTION DEFINITIONS

=============================================================================*/

/*===========================================================================
FUNCTION  PRINT_USAGE

DESCRIPTION
    This function prints out the program usage

DEPENDENCIES

RETURN VALUE

SIDE EFFECTS

===========================================================================*/

void print_usage(char *filename)
{
  printf("This program takes in an ELF file and a scatter load file\n"
         "and modifies the Program Header flags in ELF file according to the Scatter Loader\n"
         "We modify the Second Byte of P_flags field in the Program Header to mark a segment as \n "
         "Paged/nonpaged/unused/shared"
         "Usage: %s [-d] elf_file scl_file \n"
		 "      -d           - debug mode\n"
         "      elf_file     - input ELF file generated by the linker\n"
         "      scl_file     - input progressive boot scatter load file\n", filename, filename);
}


/*===========================================================================

FUNCTION    change_segment_type

DESCRIPTION


DEPENDENCIES
    None.

RETURN VALUE
    !=0  Error
    0    Success

SIDE EFFECTS
    None.

===========================================================================*/
int change_segment_type
(
 FILE *elf_file,   /* input elf file.  */
 segments_t *segs /* segment information */
)
{
  struct elf_file_info src_file;

  int i, size;
  Elf32_Phdr *i_hdr;
  unsigned int ret;
  fpos_t curr_pos;

  src_file.fd = fileno(elf_file);

  /*
   ** Verify the ELF header
   */

  size = fread((char*) &(src_file.elf_hdr), ELF_HDR_SIZE,1,elf_file);
  if (size != 1)
  {
    printf("Couldn't read elf header\n");
    return errno;
  }

  ret = verify_elf_header(&src_file.elf_hdr);
  if (ret)
  {
    printf("ELF header fails verification\n");
    return ERROR;
  }

  /* Check # of segments is the same as the scl file */
  if(segs->num_segments != src_file.elf_hdr.e_phnum)
  {
    printf("SCL file has %d segments, but found %d in ELF file!\n",
        segs->num_segments, src_file.elf_hdr.e_phnum);
    return ERROR;
  }



  /*----------------------------------------------------------------------
   ** Go to the start of the program header table in input file
   ----------------------------------------------------------------------*/
  if (fseek(elf_file, src_file.elf_hdr.e_phoff, SEEK_SET))
  {
    printf("Couldn't seek input file - errno(%d).\n", errno);
    return errno;
  }


  /*----------------------------------------------------------------------
   * What to do here?
   * 1) Change the p_type of the Program Header to the one Interpreted
        by the Scatter Loader file
   *----------------------------------------------------------------------*/
  for(i=1; i<=src_file.elf_hdr.e_phnum ; i++)
  {
    i_hdr = &src_file.phdr_table[i];


    DEBUG("file position before read is %x\n", ftell(elf_file),0,0);

    if(fgetpos(elf_file,&curr_pos))
    {
      printf("fgetpos failed\n");
      return errno;
     }

    /* Get the segment description */
    if((fread((char*) i_hdr, src_file.elf_hdr.e_phentsize,1,elf_file)) != 1)
    {
      printf("Unable to read program header!\n");
      return errno;
    }


    DEBUG("Segment[%d]: offset[%x] vaddr[%x]", i, i_hdr->p_offset, i_hdr->p_vaddr);
	DEBUG(" type[%x] size[%x] memsz[%x]\n", i_hdr->p_flags, i_hdr->p_filesz, i_hdr->p_memsz);

    /* Update flags (i-1 as before) */
    /* Use the Second Byte to store this info,
       As second Byte of p_flags is not used by the standard ELF format */
   DEBUG("p_flags  segments->flag Before Change [%#x] [%#x] :\n",i_hdr->p_flags,segs->segments[i-1].flag,0);
    i_hdr->p_flags = ((i_hdr->p_flags & ~MI_PBT_FLAGS_MASK) | (segs->segments[i-1].flag));
   DEBUG("p_flags  segments->flag After Change [%#x] [%#x] :\n",i_hdr->p_flags,segs->segments[i-1].flag,0);



    /* Write the program Header back to the file */

    if(fsetpos(elf_file,&curr_pos))
    {
      printf("fsetpos failed\n");
      return errno;
     }

    DEBUG("file position before write is %x\n", ftell(elf_file),0,0);

    if((fwrite((char*) i_hdr, src_file.elf_hdr.e_phentsize,1,elf_file)) != 1)
    {
      printf("Unable to Write program header!\n");
      return errno;
    }
    DEBUG("file position after write is %x\n\n", ftell(elf_file),0,0);

    /* Compensate for an apparent bug in cygwin file i/o. Without this,
       a subsequent read from elf_file can return incorrect data. */
    fflush(elf_file);
  }

  return 0;
}


/*===========================================================================

FUNCTION    MAIN

DESCRIPTION
    Main program function

    Usage: modify_elf_flags [-d] elf_file scl_file


DEPENDENCIES
    None.

RETURN VALUE
    !=0  Error
    0    Success

SIDE EFFECTS
    None.

===========================================================================*/
int main(int argc, char **argv)
{
  /* argv[1] = input elf
   * argv[2] = input scl file
   */
  segments_t segment_info = {0};          /* table containing segment info */

  char *in_elf_file, *in_scl_file;
  FILE *in_elf, *in_scl;
  int i=0, ret;

  if((argc == 4) && strcmp(argv[1], "-d") == 0)
  {
	    /* Enable Debug Mode */
    printf("Debug mode is enabled \n");
    debug_print = true;
    /* shift argv by 1 */
    i=1;
  }
  else if(argc != 4 && argc != 3)
  {
    print_usage(argv[0]);
    exit(-1);
  }

    in_elf_file = argv[1+i];
    in_scl_file = argv[2+i];


  OPENFILE(in_scl_file, in_scl, "rb");
  printf("Parse scatter load file %s\n", in_scl_file);

  if(parse_scl_file(in_scl, &segment_info))
  {
    perror("Error parsing scl file");
    exit(-1);
  }

  fclose(in_scl);

    OPENFILE(in_elf_file, in_elf, "rb+");
    if(change_segment_type(in_elf, &segment_info)){
         perror("Error Changing ELF program Header p_flags");
         exit(-1);
    }
    fclose(in_elf);
    return 0;
}

