#ifndef MSMHWIODM_H
#define MSMHWIODM_H
/*==========================================================================

                   HWIO Data Mover Porting Header File

DESCRIPTION
  This file contains HWIO porting definitions for all Data Mover devices
  in the target MSM.

INITIALIZATION AND SEQUENCING REQUIREMENTS
  None

Copyright (c) 2006 by QUALCOMM, Incorporated.  All Rights Reserved.
===========================================================================*/

/*============================================================================

                      EDIT HISTORY FOR FILE

 This section contains comments describing changes made to this file.
 Notice that changes are listed in reverse chronological order.

 $Header: //depot/asic/qsc1100/drivers/hw/msmhwiodm.h#1 $ $DateTime: 2007/05/17 13:25:59 $ $Author: hvo $

 when      who    what, where, why
 --------  -----  ----------------------------------------------------------
 10/20/06  amw    Updated for SC2X.
 12/07/05  jc     Initial release.

============================================================================*/

/*============================================================================
*                         INCLUDE FILES
============================================================================*/

/*============================================================================
*                         MACRO DEFINITIONS
============================================================================*/

/*
 * Create a pseudo Data Mover device to use as a template for all
 * Data Mover register field accesses.
 */
#define HWIO_DMd_CHn_CMD_PTR_SDc_RMSK                                HWIO_MDM_HI0_CHn_CMD_PTR_SDs_RMSK
#define HWIO_DMd_CHn_CMD_PTR_SDc_SHFT                                HWIO_MDM_HI0_CHn_CMD_PTR_SDs_SHFT
#define HWIO_DMd_CHn_CMD_PTR_SDc_PT_BMSK                             HWIO_MDM_HI0_CHn_CMD_PTR_SDs_PT_BMSK
#define HWIO_DMd_CHn_CMD_PTR_SDc_PT_SHFT                             HWIO_MDM_HI0_CHn_CMD_PTR_SDs_PT_SHFT
#define HWIO_DMd_CHn_CMD_PTR_SDc_ADDR_BMSK                           HWIO_MDM_HI0_CHn_CMD_PTR_SDs_ADDR_BMSK
#define HWIO_DMd_CHn_CMD_PTR_SDc_ADDR_SHFT                           HWIO_MDM_HI0_CHn_CMD_PTR_SDs_ADDR_SHFT
#define HWIO_DMd_CHn_RSLT_SDc_RMSK                                   HWIO_MDM_HI0_CHn_RSLT_SDs_RMSK
#define HWIO_DMd_CHn_RSLT_SDc_SHFT                                   HWIO_MDM_HI0_CHn_RSLT_SDs_SHFT
#define HWIO_DMd_CHn_RSLT_SDc_V_BMSK                                 HWIO_MDM_HI0_CHn_RSLT_SDs_V_BMSK
#define HWIO_DMd_CHn_RSLT_SDc_V_SHFT                                 HWIO_MDM_HI0_CHn_RSLT_SDs_V_SHFT
#define HWIO_DMd_CHn_RSLT_SDc_ERR_BMSK                               HWIO_MDM_HI0_CHn_RSLT_SDs_ERR_BMSK
#define HWIO_DMd_CHn_RSLT_SDc_ERR_SHFT                               HWIO_MDM_HI0_CHn_RSLT_SDs_ERR_SHFT
#define HWIO_DMd_CHn_RSLT_SDc_F_BMSK                                 HWIO_MDM_HI0_CHn_RSLT_SDs_F_BMSK
#define HWIO_DMd_CHn_RSLT_SDc_F_SHFT                                 HWIO_MDM_HI0_CHn_RSLT_SDs_F_SHFT
#define HWIO_DMd_CHn_RSLT_SDc_TPD_BMSK                               HWIO_MDM_HI0_CHn_RSLT_SDs_TPD_BMSK
#define HWIO_DMd_CHn_RSLT_SDc_TPD_SHFT                               HWIO_MDM_HI0_CHn_RSLT_SDs_TPD_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_RMSK                           HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_RMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_SHFT                           HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_FLUSH_TYPE_BMSK                HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_FLUSH_TYPE_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_FLUSH_TYPE_SHFT                HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_FLUSH_TYPE_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_CMD_ERR_BMSK                   HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_CMD_ERR_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_CMD_ERR_SHFT                   HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_CMD_ERR_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_LAST_CPLE_MPU_BMSK             HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_LAST_CPLE_MPU_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_LAST_CPLE_MPU_SHFT             HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_LAST_CPLE_MPU_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_NO_OTB_INSTR_BMSK              HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_NO_OTB_INSTR_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_NO_OTB_INSTR_SHFT              HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_NO_OTB_INSTR_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_NO_INB_INSTR_BMSK              HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_NO_INB_INSTR_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_NO_INB_INSTR_SHFT              HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_NO_INB_INSTR_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_NO_DATA_XFER_BMSK              HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_NO_DATA_XFER_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_NO_DATA_XFER_SHFT              HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_NO_DATA_XFER_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_DPH_CMD_TYPE_BMSK              HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_DPH_CMD_TYPE_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_DPH_CMD_TYPE_SHFT              HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_DPH_CMD_TYPE_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_PTR_NUM_OVRFLW_BMSK            HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_PTR_NUM_OVRFLW_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_PTR_NUM_OVRFLW_SHFT            HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_PTR_NUM_OVRFLW_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_DSCR_INDX_OVRFLW_BMSK          HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_DSCR_INDX_OVRFLW_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_DSCR_INDX_OVRFLW_SHFT          HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_DSCR_INDX_OVRFLW_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_LEN_ERROR_BMSK                 HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_LEN_ERROR_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_LEN_ERROR_SHFT                 HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_LEN_ERROR_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_MPU_ERROR_BMSK                 HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_MPU_ERROR_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_MPU_ERROR_SHFT                 HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_MPU_ERROR_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_DPH_BUS_ERROR_BMSK             HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_DPH_BUS_ERROR_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_DPH_BUS_ERROR_SHFT             HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_DPH_BUS_ERROR_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_CPH_BUS_ERROR_BMSK             HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_CPH_BUS_ERROR_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_CPH_BUS_ERROR_SHFT             HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_CPH_BUS_ERROR_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_CH_STATE_BMSK                  HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_CH_STATE_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_CH_STATE_SHFT                  HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_CH_STATE_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_V_BMSK                         HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_V_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE0_SDc_V_SHFT                         HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_V_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE1_SDc_RMSK                           HWIO_MDM_HI0_CHn_FLUSH_STATE1_SDs_RMSK
#define HWIO_DMd_CHn_FLUSH_STATE1_SDc_SHFT                           HWIO_MDM_HI0_CHn_FLUSH_STATE1_SDs_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE1_SDc_CMD_ADDR_BMSK                  HWIO_MDM_HI0_CHn_FLUSH_STATE1_SDs_CMD_ADDR_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE1_SDc_CMD_ADDR_SHFT                  HWIO_MDM_HI0_CHn_FLUSH_STATE1_SDs_CMD_ADDR_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE2_SDc_RMSK                           HWIO_MDM_HI0_CHn_FLUSH_STATE2_SDs_RMSK
#define HWIO_DMd_CHn_FLUSH_STATE2_SDc_SHFT                           HWIO_MDM_HI0_CHn_FLUSH_STATE2_SDs_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE2_SDc_CMD_ADDR_BMSK                  HWIO_MDM_HI0_CHn_FLUSH_STATE2_SDs_CMD_ADDR_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE2_SDc_CMD_ADDR_SHFT                  HWIO_MDM_HI0_CHn_FLUSH_STATE2_SDs_CMD_ADDR_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE3_SDc_RMSK                           HWIO_MDM_HI0_CHn_FLUSH_STATE3_SDs_RMSK
#define HWIO_DMd_CHn_FLUSH_STATE3_SDc_SHFT                           HWIO_MDM_HI0_CHn_FLUSH_STATE3_SDs_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE3_SDc_DST_REM_LEN_BMSK               HWIO_MDM_HI0_CHn_FLUSH_STATE3_SDs_DST_REM_LEN_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE3_SDc_DST_REM_LEN_SHFT               HWIO_MDM_HI0_CHn_FLUSH_STATE3_SDs_DST_REM_LEN_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE3_SDc_SRC_REM_LEN_BMSK               HWIO_MDM_HI0_CHn_FLUSH_STATE3_SDs_SRC_REM_LEN_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE3_SDc_SRC_REM_LEN_SHFT               HWIO_MDM_HI0_CHn_FLUSH_STATE3_SDs_SRC_REM_LEN_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE4_SDc_RMSK                           HWIO_MDM_HI0_CHn_FLUSH_STATE4_SDs_RMSK
#define HWIO_DMd_CHn_FLUSH_STATE4_SDc_SHFT                           HWIO_MDM_HI0_CHn_FLUSH_STATE4_SDs_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE4_SDc_DST_DSCR_NUM_BMSK              HWIO_MDM_HI0_CHn_FLUSH_STATE4_SDs_DST_DSCR_NUM_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE4_SDc_DST_DSCR_NUM_SHFT              HWIO_MDM_HI0_CHn_FLUSH_STATE4_SDs_DST_DSCR_NUM_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE4_SDc_SRC_DSCR_NUM_BMSK              HWIO_MDM_HI0_CHn_FLUSH_STATE4_SDs_SRC_DSCR_NUM_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE4_SDc_SRC_DSCR_NUM_SHFT              HWIO_MDM_HI0_CHn_FLUSH_STATE4_SDs_SRC_DSCR_NUM_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE5_SDc_RMSK                           HWIO_MDM_HI0_CHn_FLUSH_STATE5_SDs_RMSK
#define HWIO_DMd_CHn_FLUSH_STATE5_SDc_SHFT                           HWIO_MDM_HI0_CHn_FLUSH_STATE5_SDs_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE5_SDc_PTR_NUM_BMSK                   HWIO_MDM_HI0_CHn_FLUSH_STATE5_SDs_PTR_NUM_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE5_SDc_PTR_NUM_SHFT                   HWIO_MDM_HI0_CHn_FLUSH_STATE5_SDs_PTR_NUM_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE5_SDc_DSCR_INDX_NUM_BMSK             HWIO_MDM_HI0_CHn_FLUSH_STATE5_SDs_DSCR_INDX_NUM_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE5_SDc_DSCR_INDX_NUM_SHFT             HWIO_MDM_HI0_CHn_FLUSH_STATE5_SDs_DSCR_INDX_NUM_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE5_SDc_BUFFERED_LEN_BMSK              HWIO_MDM_HI0_CHn_FLUSH_STATE5_SDs_BUFFERED_LEN_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE5_SDc_BUFFERED_LEN_SHFT              HWIO_MDM_HI0_CHn_FLUSH_STATE5_SDs_BUFFERED_LEN_SHFT
#define HWIO_DMd_CHn_FLUSH_STATE5_SDc_IND_LEVEL_BMSK                 HWIO_MDM_HI0_CHn_FLUSH_STATE5_SDs_IND_LEVEL_BMSK
#define HWIO_DMd_CHn_FLUSH_STATE5_SDc_IND_LEVEL_SHFT                 HWIO_MDM_HI0_CHn_FLUSH_STATE5_SDs_IND_LEVEL_SHFT
#define HWIO_DMd_CHn_STATUS_SDc_RMSK                                 HWIO_MDM_HI0_CHn_STATUS_SDs_RMSK
#define HWIO_DMd_CHn_STATUS_SDc_SHFT                                 HWIO_MDM_HI0_CHn_STATUS_SDs_SHFT
#define HWIO_DMd_CHn_STATUS_SDc_RSLT_FIFO_CNTR_BMSK                  HWIO_MDM_HI0_CHn_STATUS_SDs_RSLT_FIFO_CNTR_BMSK
#define HWIO_DMd_CHn_STATUS_SDc_RSLT_FIFO_CNTR_SHFT                  HWIO_MDM_HI0_CHn_STATUS_SDs_RSLT_FIFO_CNTR_SHFT
#define HWIO_DMd_CHn_STATUS_SDc_CMD_PTR_FIFO_CNTR_BMSK               HWIO_MDM_HI0_CHn_STATUS_SDs_CMD_PTR_FIFO_CNTR_BMSK
#define HWIO_DMd_CHn_STATUS_SDc_CMD_PTR_FIFO_CNTR_SHFT               HWIO_MDM_HI0_CHn_STATUS_SDs_CMD_PTR_FIFO_CNTR_SHFT
#define HWIO_DMd_CHn_STATUS_SDc_CMD_IN_PROGRESS_BMSK                 HWIO_MDM_HI0_CHn_STATUS_SDs_CMD_IN_PROGRESS_BMSK
#define HWIO_DMd_CHn_STATUS_SDc_CMD_IN_PROGRESS_SHFT                 HWIO_MDM_HI0_CHn_STATUS_SDs_CMD_IN_PROGRESS_SHFT
#define HWIO_DMd_CHn_STATUS_SDc_RSLT_VLD_BMSK                        HWIO_MDM_HI0_CHn_STATUS_SDs_RSLT_VLD_BMSK
#define HWIO_DMd_CHn_STATUS_SDc_RSLT_VLD_SHFT                        HWIO_MDM_HI0_CHn_STATUS_SDs_RSLT_VLD_SHFT
#define HWIO_DMd_CHn_STATUS_SDc_CMD_PTR_RDY_BMSK                     HWIO_MDM_HI0_CHn_STATUS_SDs_CMD_PTR_RDY_BMSK
#define HWIO_DMd_CHn_STATUS_SDc_CMD_PTR_RDY_SHFT                     HWIO_MDM_HI0_CHn_STATUS_SDs_CMD_PTR_RDY_SHFT
#define HWIO_DMd_CHn_CONF_RMSK                                       HWIO_MDM_HI0_CHn_CONF_RMSK
#define HWIO_DMd_CHn_CONF_SHFT                                       HWIO_MDM_HI0_CHn_CONF_SHFT
#define HWIO_DMd_CHn_CONF_OTHER_CH_BLK_MASK_BMSK                     HWIO_MDM_HI0_CHn_CONF_OTHER_CH_BLK_MASK_BMSK
#define HWIO_DMd_CHn_CONF_OTHER_CH_BLK_MASK_SHFT                     HWIO_MDM_HI0_CHn_CONF_OTHER_CH_BLK_MASK_SHFT
#define HWIO_DMd_CHn_CONF_MPU_DISABLE_BMSK                           HWIO_MDM_HI0_CHn_CONF_MPU_DISABLE_BMSK
#define HWIO_DMd_CHn_CONF_MPU_DISABLE_SHFT                           HWIO_MDM_HI0_CHn_CONF_MPU_DISABLE_SHFT
#define HWIO_DMd_CHn_CONF_PERM_IND_MPU_CONF_BMSK                     HWIO_MDM_HI0_CHn_CONF_PERM_IND_MPU_CONF_BMSK
#define HWIO_DMd_CHn_CONF_PERM_IND_MPU_CONF_SHFT                     HWIO_MDM_HI0_CHn_CONF_PERM_IND_MPU_CONF_SHFT
#define HWIO_DMd_CHn_CONF_PERM_MPU_CONF_BMSK                         HWIO_MDM_HI0_CHn_CONF_PERM_MPU_CONF_BMSK
#define HWIO_DMd_CHn_CONF_PERM_MPU_CONF_SHFT                         HWIO_MDM_HI0_CHn_CONF_PERM_MPU_CONF_SHFT
#define HWIO_DMd_CHn_CONF_FORCE_TOP_PTR_RSLT_BMSK                    HWIO_MDM_HI0_CHn_CONF_FORCE_TOP_PTR_RSLT_BMSK
#define HWIO_DMd_CHn_CONF_FORCE_TOP_PTR_RSLT_SHFT                    HWIO_MDM_HI0_CHn_CONF_FORCE_TOP_PTR_RSLT_SHFT
#define HWIO_DMd_CHn_CONF_FORCE_FLUSH_RSLT_BMSK                      HWIO_MDM_HI0_CHn_CONF_FLUSH_RSLT_EN_BMSK
#define HWIO_DMd_CHn_CONF_FORCE_FLUSH_RSLT_SHFT                      HWIO_MDM_HI0_CHn_CONF_FLUSH_RSLT_EN_SHFT
#define HWIO_DMd_CHn_CONF_IRQ_EN_BMSK                                HWIO_MDM_HI0_CHn_CONF_IRQ_EN_BMSK
#define HWIO_DMd_CHn_CONF_IRQ_EN_SHFT                                HWIO_MDM_HI0_CHn_CONF_IRQ_EN_SHFT
#define HWIO_DMd_CHn_CONF_SEC_DOMAIN_BMSK                            HWIO_MDM_HI0_CHn_CONF_SEC_DOMAIN_BMSK
#define HWIO_DMd_CHn_CONF_SEC_DOMAIN_SHFT                            HWIO_MDM_HI0_CHn_CONF_SEC_DOMAIN_SHFT
#define HWIO_DMd_CHn_CONF_PRIORITY_BMSK                              HWIO_MDM_HI0_CHn_CONF_PRIORITY_BMSK
#define HWIO_DMd_CHn_CONF_PRIORITY_SHFT                              HWIO_MDM_HI0_CHn_CONF_PRIORITY_SHFT
#define HWIO_DMd_CHn_CONF_RSLT_CONF_SHADOW_EN_BMSK                   HWIO_MDM_HI0_CHn_CONF_RSLT_CONF_SHADOW_EN_BMSK
#define HWIO_DMd_CHn_CONF_RSLT_CONF_SHADOW_EN_SHFT                   HWIO_MDM_HI0_CHn_CONF_RSLT_CONF_SHADOW_EN_SHFT
#define HWIO_DMd_CHn_DBG_0_RMSK                                      HWIO_MDM_HI0_CHn_DBG_0_RMSK
#define HWIO_DMd_CHn_DBG_0_SHFT                                      HWIO_MDM_HI0_CHn_DBG_0_SHFT
#define HWIO_DMd_CHn_DBG_0_REQ_ENG_HALT_BMSK                         HWIO_MDM_HI0_CHn_DBG_0_REQ_ENG_HALT_BMSK
#define HWIO_DMd_CHn_DBG_0_REQ_ENG_HALT_SHFT                         HWIO_MDM_HI0_CHn_DBG_0_REQ_ENG_HALT_SHFT
#define HWIO_DMd_CHn_DBG_0_CMD_ENG_HALT_BMSK                         HWIO_MDM_HI0_CHn_DBG_0_CMD_ENG_HALT_BMSK
#define HWIO_DMd_CHn_DBG_0_CMD_ENG_HALT_SHFT                         HWIO_MDM_HI0_CHn_DBG_0_CMD_ENG_HALT_SHFT
#define HWIO_DMd_CHn_DBG_0_CMD_PTR_FIFO_HALT_BMSK                    HWIO_MDM_HI0_CHn_DBG_0_CMD_PTR_FIFO_HALT_BMSK
#define HWIO_DMd_CHn_DBG_0_CMD_PTR_FIFO_HALT_SHFT                    HWIO_MDM_HI0_CHn_DBG_0_CMD_PTR_FIFO_HALT_SHFT
#define HWIO_DMd_CHn_DBG_0_ERROR_BMSK                                HWIO_MDM_HI0_CHn_DBG_0_ERROR_BMSK
#define HWIO_DMd_CHn_DBG_0_ERROR_SHFT                                HWIO_MDM_HI0_CHn_DBG_0_ERROR_SHFT
#define HWIO_DMd_CHn_DBG_1_RMSK                                      HWIO_MDM_HI0_CHn_DBG_1_RMSK
#define HWIO_DMd_CHn_DBG_1_SHFT                                      HWIO_MDM_HI0_CHn_DBG_1_SHFT
#define HWIO_DMd_CHn_DBG_1_DBG_STATE_BMSK                            HWIO_MDM_HI0_CHn_DBG_1_DBG_STATE_BMSK
#define HWIO_DMd_CHn_DBG_1_DBG_STATE_SHFT                            HWIO_MDM_HI0_CHn_DBG_1_DBG_STATE_SHFT
#define HWIO_DMd_CHn_RSLT_CONF_SDc_FORCE_TOP_PTR_RSLT_BMSK           HWIO_MDM_HI0_CHn_RSLT_CONF_SDc_FORCE_TOP_PTR_RSLT_BMSK
#define HWIO_DMd_CHn_RSLT_CONF_SDc_FORCE_TOP_PTR_RSLT_SHFT           HWIO_MDM_HI0_CHn_RSLT_CONF_SDc_FORCE_TOP_PTR_RSLT_SHFT
#define HWIO_DMd_CHn_RSLT_CONF_SDc_FORCE_FLUSH_RSLT_BMSK             HWIO_MDM_HI0_CHn_RSLT_CONF_SDs_FLUSH_RSLT_EN_BMSK
#define HWIO_DMd_CHn_RSLT_CONF_SDc_FORCE_FLUSH_RSLT_SHFT             HWIO_MDM_HI0_CHn_RSLT_CONF_SDs_FLUSH_RSLT_EN_SHFT
#define HWIO_DMd_CHn_RSLT_CONF_SDc_IRQ_EN_BMSK                       HWIO_MDM_HI0_CHn_RSLT_CONF_SDs_IRQ_EN_BMSK
#define HWIO_DMd_CHn_RSLT_CONF_SDc_IRQ_EN_SHFT                       HWIO_MDM_HI0_CHn_RSLT_CONF_SDs_IRQ_EN_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_RMSK                      HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_RMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_SHFT                      HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_15_IRQ_BMSK            HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_15_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_15_IRQ_SHFT            HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_15_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_14_IRQ_BMSK            HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_14_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_14_IRQ_SHFT            HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_14_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_13_IRQ_BMSK            HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_13_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_13_IRQ_SHFT            HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_13_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_12_IRQ_BMSK            HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_12_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_12_IRQ_SHFT            HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_12_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_11_IRQ_BMSK            HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_11_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_11_IRQ_SHFT            HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_11_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_10_IRQ_BMSK            HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_10_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_10_IRQ_SHFT            HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_10_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_9_IRQ_BMSK             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_9_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_9_IRQ_SHFT             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_9_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_8_IRQ_BMSK             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_8_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_8_IRQ_SHFT             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_8_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_7_IRQ_BMSK             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_7_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_7_IRQ_SHFT             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_7_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_6_IRQ_BMSK             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_6_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_6_IRQ_SHFT             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_6_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_5_IRQ_BMSK             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_5_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_5_IRQ_SHFT             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_5_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_4_IRQ_BMSK             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_4_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_4_IRQ_SHFT             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_4_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_3_IRQ_BMSK             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_3_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_3_IRQ_SHFT             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_3_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_2_IRQ_BMSK             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_2_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_2_IRQ_SHFT             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_2_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_1_IRQ_BMSK             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_1_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_1_IRQ_SHFT             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_1_IRQ_SHFT
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_0_IRQ_BMSK             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_0_IRQ_BMSK
#define HWIO_DMd_SEC_DOMAIN_IRQ_STATUS_SDc_CH_0_IRQ_SHFT             HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_CH_0_IRQ_SHFT
#define HWIO_DMd_CIn_CONF_RMSK                                       HWIO_MDM_HI0_CIn_CONF_RMSK
#define HWIO_DMd_CIn_CONF_SHFT                                       HWIO_MDM_HI0_CIn_CONF_SHFT
#define HWIO_DMd_CIn_CONF_RANGE_END_BMSK                             HWIO_MDM_HI0_CIn_CONF_RANGE_END_BMSK
#define HWIO_DMd_CIn_CONF_RANGE_END_SHFT                             HWIO_MDM_HI0_CIn_CONF_RANGE_END_SHFT
#define HWIO_DMd_CIn_CONF_RANGE_START_BMSK                           HWIO_MDM_HI0_CIn_CONF_RANGE_START_BMSK
#define HWIO_DMd_CIn_CONF_RANGE_START_SHFT                           HWIO_MDM_HI0_CIn_CONF_RANGE_START_SHFT
#define HWIO_DMd_CIn_CONF_MAX_BURST_LEN_BMSK                         HWIO_MDM_HI0_CIn_CONF_MAX_BURST_LEN_BMSK
#define HWIO_DMd_CIn_CONF_MAX_BURST_LEN_SHFT                         HWIO_MDM_HI0_CIn_CONF_MAX_BURST_LEN_SHFT
#define HWIO_DMd_CIn_DBG_ERR_RMSK                                    HWIO_MDM_HI0_CIn_DBG_ERR_RMSK
#define HWIO_DMd_CIn_DBG_ERR_SHFT                                    HWIO_MDM_HI0_CIn_DBG_ERR_SHFT
#define HWIO_DMd_CIn_DBG_ERR_DATA_BUS_ERR_MASK_BMSK                  HWIO_MDM_HI0_CIn_DBG_ERR_DATA_BUS_ERR_BMSK
#define HWIO_DMd_CIn_DBG_ERR_DATA_BUS_ERR_MASK_SHFT                  HWIO_MDM_HI0_CIn_DBG_ERR_DATA_BUS_ERR_SHFT
#define HWIO_DMd_CIn_DBG_ERR_CMD_BUS_ERR_MASK_BMSK                   HWIO_MDM_HI0_CIn_DBG_ERR_CMD_BUS_ERR_BMSK
#define HWIO_DMd_CIn_DBG_ERR_CMD_BUS_ERR_MASK_SHFT                   HWIO_MDM_HI0_CIn_DBG_ERR_CMD_BUS_ERR_SHFT
#define HWIO_DMd_CIn_DBG_ERR_CLR_RMSK                                HWIO_MDM_HI0_CIn_DBG_ERR_CLR_RMSK
#define HWIO_DMd_CIn_DBG_ERR_CLR_SHFT                                HWIO_MDM_HI0_CIn_DBG_ERR_CLR_SHFT
#define HWIO_DMd_CIn_DBG_ERR_CLR_CI_ERR_CLR_CHAN_NUM_BMSK            HWIO_MDM_HI0_CIn_DBG_ERR_CLR_CI_ERR_CLR_CHAN_NUM_BMSK
#define HWIO_DMd_CIn_DBG_ERR_CLR_CI_ERR_CLR_CHAN_NUM_SHFT            HWIO_MDM_HI0_CIn_DBG_ERR_CLR_CI_ERR_CLR_CHAN_NUM_SHFT
#define HWIO_DMd_CRCI_DBG_RMSK                                       HWIO_MDM_HI0_CRCI_DBG_RMSK
#define HWIO_DMd_CRCI_DBG_SHFT                                       HWIO_MDM_HI0_CRCI_DBG_SHFT
#define HWIO_DMd_CRCI_DBG_CRCI_RST_BMSK                              HWIO_MDM_HI0_CRCI_DBG_CRCI_RST_BMSK
#define HWIO_DMd_CRCI_DBG_CRCI_RST_SHFT                              HWIO_MDM_HI0_CRCI_DBG_CRCI_RST_SHFT
#define HWIO_DMd_GLBL_DBG_CMD_ENG_RMSK                               HWIO_MDM_HI0_GLBL_DBG_CMD_ENG_RMSK
#define HWIO_DMd_GLBL_DBG_CMD_ENG_SHFT                               HWIO_MDM_HI0_GLBL_DBG_CMD_ENG_SHFT
#define HWIO_DMd_GLBL_DBG_CMD_ENG_DBG_STATE_BMSK                     HWIO_MDM_HI0_GLBL_DBG_CMD_ENG_DBG_STATE_BMSK
#define HWIO_DMd_GLBL_DBG_CMD_ENG_DBG_STATE_SHFT                     HWIO_MDM_HI0_GLBL_DBG_CMD_ENG_DBG_STATE_SHFT
#define HWIO_DMd_GLBL_DBG_REQ_ENG_RMSK                               HWIO_MDM_HI0_GLBL_DBG_REQ_ENG_RMSK
#define HWIO_DMd_GLBL_DBG_REQ_ENG_SHFT                               HWIO_MDM_HI0_GLBL_DBG_REQ_ENG_SHFT
#define HWIO_DMd_GLBL_DBG_REQ_ENG_DBG_STATE_BMSK                     HWIO_MDM_HI0_GLBL_DBG_REQ_ENG_DBG_STATE_BMSK
#define HWIO_DMd_GLBL_DBG_REQ_ENG_DBG_STATE_SHFT                     HWIO_MDM_HI0_GLBL_DBG_REQ_ENG_DBG_STATE_SHFT
#define HWIO_DMd_GLBL_DBG_XFR_ENG_RMSK                               HWIO_MDM_HI0_GLBL_DBG_XFR_ENG_RMSK
#define HWIO_DMd_GLBL_DBG_XFR_ENG_SHFT                               HWIO_MDM_HI0_GLBL_DBG_XFR_ENG_SHFT
#define HWIO_DMd_GLBL_DBG_XFR_ENG_DBG_STATE_BMSK                     HWIO_MDM_HI0_GLBL_DBG_XFR_ENG_DBG_STATE_BMSK
#define HWIO_DMd_GLBL_DBG_XFR_ENG_DBG_STATE_SHFT                     HWIO_MDM_HI0_GLBL_DBG_XFR_ENG_DBG_STATE_SHFT
#define HWIO_DMd_GLBL_DBG_CHAN_BLK_RMSK                              HWIO_MDM_HI0_GLBL_DBG_CHAN_BLK_RMSK
#define HWIO_DMd_GLBL_DBG_CHAN_BLK_SHFT                              HWIO_MDM_HI0_GLBL_DBG_CHAN_BLK_SHFT
#define HWIO_DMd_GLBL_DBG_CHAN_BLK_CHAN_BLK_MASK_BMSK                HWIO_MDM_HI0_GLBL_DBG_CHAN_BLK_CHAN_BLK_MASK_BMSK
#define HWIO_DMd_GLBL_DBG_CHAN_BLK_CHAN_BLK_MASK_SHFT                HWIO_MDM_HI0_GLBL_DBG_CHAN_BLK_CHAN_BLK_MASK_SHFT
#define HWIO_DMd_GLBL_DBG_CHAN_BLK_CLR_RMSK                          HWIO_MDM_HI0_GLBL_DBG_CHAN_BLK_CLR_RMSK
#define HWIO_DMd_GLBL_DBG_CHAN_BLK_CLR_SHFT                          HWIO_MDM_HI0_GLBL_DBG_CHAN_BLK_CLR_SHFT
#define HWIO_DMd_GLBL_DBG_CHAN_BLK_CLR_CHAN_BLK_CLR_CHAN_NNUM_BMSK   HWIO_MDM_HI0_GLBL_DBG_CHAN_BLK_CLR_CHAN_BLK_CLR_CHAN_NNUM_BMSK
#define HWIO_DMd_GLBL_DBG_CHAN_BLK_CLR_CHAN_BLK_CLR_CHAN_NNUM_SHFT   HWIO_MDM_HI0_GLBL_DBG_CHAN_BLK_CLR_CHAN_BLK_CLR_CHAN_NNUM_SHFT

#define HWIO_MDM_CHn_CMD_PTR_SDc_ADDR(index1, index2)                HWIO_MDM_HI0_CHn_CMD_PTR_SDs_ADDR(index1, index2)
#define HWIO_MDM_CHn_CMD_PTR_SDc_OUTI2(index1, index2, val)          HWIO_MDM_HI0_CHn_CMD_PTR_SDs_OUTI2(index1, index2, val)
#define HWIO_MDM_CHn_RSLT_SDc_ADDR(index1, index2)                   HWIO_MDM_HI0_CHn_RSLT_SDs_ADDR(index1, index2)
#define HWIO_MDM_CHn_RSLT_SDc_INI2(index1, index2)                   HWIO_MDM_HI0_CHn_RSLT_SDs_INI2(index1, index2)
#define HWIO_MDM_CHn_FLUSH_STATE0_SDc_ADDR(index1, index2)           HWIO_MDM_HI0_CHn_FLUSH_STATE0_SDs_ADDR(index1, index2)
#define HWIO_MDM_CHn_FLUSH_STATE1_SDc_ADDR(index1, index2)           HWIO_MDM_HI0_CHn_FLUSH_STATE1_SDs_ADDR(index1, index2)
#define HWIO_MDM_CHn_FLUSH_STATE2_SDc_ADDR(index1, index2)           HWIO_MDM_HI0_CHn_FLUSH_STATE2_SDs_ADDR(index1, index2)
#define HWIO_MDM_CHn_FLUSH_STATE3_SDc_ADDR(index1, index2)           HWIO_MDM_HI0_CHn_FLUSH_STATE3_SDs_ADDR(index1, index2)
#define HWIO_MDM_CHn_FLUSH_STATE4_SDc_ADDR(index1, index2)           HWIO_MDM_HI0_CHn_FLUSH_STATE4_SDs_ADDR(index1, index2)
#define HWIO_MDM_CHn_FLUSH_STATE5_SDc_ADDR(index1, index2)           HWIO_MDM_HI0_CHn_FLUSH_STATE5_SDs_ADDR(index1, index2)
#define HWIO_MDM_CHn_CONF_ADDR(index)                                HWIO_MDM_HI0_CHn_CONF_ADDR(index);
#define HWIO_MDM_CHn_STATUS_SDc_ADDR(index1, index2)                 HWIO_MDM_HI0_CHn_STATUS_SDs_ADDR(index1, index2);
#define HWIO_MDM_CHn_DBG_0_ADDR(index)                               HWIO_MDM_HI0_CHn_DBG_0_ADDR(index)
#define HWIO_MDM_CHn_DBG_1_ADDR(index)                               HWIO_MDM_HI0_CHn_DBG_1_ADDR(index)
#define HWIO_MDM_SEC_DOMAIN_IRQ_STATUS_SDc_ADDR(index)               HWIO_MDM_HI0_SEC_DOMAIN_IRQ_STATUS_SDs_ADDR(index)
#define HWIO_MDM_CIn_CONF_ADDR(client)                               HWIO_MDM_HI0_CIn_CONF_ADDR(client)        
#define HWIO_MDM_CIn_DBG_ERR_ADDR(client)                            HWIO_MDM_HI0_CIn_DBG_ERR_ADDR(client)
#define HWIO_MDM_CRCI_DBG_ADDR                                       HWIO_MDM_HI0_CRCI_DBG_ADDR
#define HWIO_MDM_GLBL_DBG_CMD_ENG_ADDR                               HWIO_MDM_HI0_GLBL_DBG_CMD_ENG_ADDR
#define HWIO_MDM_GLBL_DBG_REQ_ENG_ADDR                               HWIO_MDM_HI0_GLBL_DBG_REQ_ENG_ADDR
#define HWIO_MDM_GLBL_DBG_XFR_ENG_ADDR                               HWIO_MDM_HI0_GLBL_DBG_XFR_ENG_ADDR
#define HWIO_MDM_GLBL_DBG_CHAN_BLK_ADDR                              HWIO_MDM_HI0_GLBL_DBG_CHAN_BLK_ADDR
#define HWIO_MDM_GLBL_DBG_CHAN_BLK_CLR_ADDR                          HWIO_MDM_HI0_GLBL_DBG_CHAN_BLK_CLR_ADDR

/* Added for Data Mover based flash drivers. */
#define HWIO_HI0_CHn_RSLT_SD0_ERR_BMSK                               HWIO_MDM_HI0_CHn_RSLT_SDs_ERR_BMSK
#define HWIO_HI0_CHn_RSLT_SD0_F_BMSK                                 HWIO_MDM_HI0_CHn_RSLT_SDs_F_BMSK

/*============================================================================
                        TYPE DECLARATIONS
============================================================================*/

/*============================================================================
                        GLOBAL DATA DECLARATIONS
============================================================================*/

/*============================================================================
*                         EXPORTED FUNCTIONS
============================================================================*/

#endif  /* MSMHWIODM_H */
