//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SunnyCat.rc
//
#define IDD_DIALOG_SETPIN               77
#define IDS_ABOUTBOX                    101
#define IDS_SIGNAL_DETECTING            102
#define IDS_DISCONNECT_PROMPT           103
#define IDS_CALL_INPUT                  104
#define IDS_CALL_TALKING                105
#define IDS_CALL_INCOME                 106
#define IDS_CALL_CALLING                107
#define IDS_CALL_FAILED                 108
#define IDS_UNKOWN                      109
#define IDS_SMS_SENDING                 110
#define IDS_CONNECT_OPEN_PORT           111
#define IDS_CONNECT_PORT_OPENED         112
#define IDS_CONNECT_OPEN_DEVICE         113
#define IDS_CONNECT_DEVICE_OPENED       114
#define IDS_CONNECT_AUTHEN              115
#define IDS_CONNECT_LINKED              116
#define IDS_CONNECT_DISCONNECTING       117
#define IDS_DELETING                    118
#define IDS_ERROR_DELETE_FAILED         119
#define IDS_USERINFO                    120
#define IDS_CLOSE                       121
#define IDS_MINIMIZE                    122
#define IDS_ERROR_NOT_OPEN_COM          123
#define IDS_SMS_SEND_FAILED             124
#define IDS_CONNECT_OFFLINE             125
#define IDS_CONNECT_CONNECTING          126
#define IDS_CONNECT_CONNECTED           127
#define IDS_SEND                        128
#define IDS_RECEIVE                     129
#define IDS_RESTORY                     130
#define IDS_NEWSMS                      131
#define IDS_PROMPT_ONLINE               132
#define IDS_LOCAL_SETTING               133
#define IDS_ERROR_HARDWARE_NOT_FOUNT    134
#define IDS_ERROR_UIM_NOT_FOUND         135
#define IDS_DETECT_SIGNAL               136
#define IDS_ERROR_MODEM_NOT_FOUND       137
#define IDS_QUIT_ONLINE_PROMPT          138
#define IDS_QUIT_CALLING_PROMPT         139
#define IDS_AUTH_NOTIFY                 140
#define IDS_REGISTERING_NETWORK         141
#define IDS_AUTH_ACK                    142
#define IDS_LOGON_NETWORK               143
#define IDS_PROMPT_CALL                 144
#define IDS_APPNAME                     145
#define IDS_CANCEL                      146
#define IDS_INSERTDEVICE_AGAIN          147
#define IDS_WAVEFILE_TYPE               148
#define IDS_ONLINE_REMOVED              149
#define IDS_NOTINSERT_FAIL              150
#define IDS_STRING_FREE                 151
#define IDS_STRING_ERRORNUM             152
#define IDS_RESTART_PC                  153
#define IDS_DRVIER_INSTALL_OK           154
#define IDS_APPRUNING                   155
#define IDB_CALL_0                      162
#define IDD_DIALOG_MSGBOX               163
#define IDB_CALLINANDOUT                163
#define IDB_CALL_3                      164
#define IDB_CALL_1                      165
#define IDB_CALL_2                      166
#define IDB_CALL_4                      169
#define IDB_CALL_5                      170
#define IDB_BITMAP_SHOW                 184
#define IDD_DIALOG_NEWCARD_SIM          185
#define IDR_MENU_CONNECTRECORD          186
#define IDD_DIALOG_NETSTAT_TIME         189
#define IDB_BITMAP0                     191
#define IDB_BITMAP1                     192
#define IDB_BITMAP2                     193
#define IDB_BITMAP3                     194
#define IDB_BITMAP4                     195
#define IDB_BITMAP5                     196
#define IDB_BITMAP6                     197
#define IDB_BITMAP7                     198
#define IDB_BITMAP8                     199
#define IDB_BITMAP9                     200
#define IDB_BITMAP11                    201
#define IDB_BITMAP12                    202
#define IDB_BITMAP_CALL                 203
#define IDB_BITMAP_HANGUP               204
#define IDB_BITMAP10                    205
#define IDB_BITMAP_CLEAR                211
#define IDB_LONGBAR                     212
#define IDB_LINKMANTREE                 213
#define IDS_APN_NEW                     214
#define IDB_SMALL_TOOLBAR               215
#define IDS_APN_EDIT                    215
#define IDS_APN_DELETE                  216
#define IDB_TOOLBAR                     217
#define IDS_APN_OK                      217
#define IDS_APN_CANCEL                  218
#define IDB_BITMAP_CONNECT              219
#define IDB_BITMAP_DOWN1                220
#define IDS_APN_NOTNULL                 220
#define IDS_APN_EXIST                   221
#define IDB_BITMAP_DOWN2                222
#define IDS_APN_CMNETNOTDEL             222
#define IDS_APN_ADVANCED                223
#define IDB_BITMAP_DOWN3                223
#define IDS_ADVANCED_SET                224
#define IDB_BITMAP_DOWN4                224
#define IDS_AUTO_IP                     225
#define IDB_BITMAP_DOWN5                225
#define IDS_STATIC_IP                   226
#define IDB_BITMAP_DOWN6                226
#define IDS_AUTO_DNS                    227
#define IDB_BITMAP_DOWN7                227
#define IDS_STATIC_DNS                  228
#define IDB_BITMAP_DOWN8                228
#define IDS_DNS_1                       229
#define IDB_BITMAP_DOWN9                229
#define IDS_DNS_2                       230
#define IDB_BITMAP_DOWN11               230
#define IDB_BITMAP_DOWN12               231
#define IDB_BITMAP_DOWNCLEAR            232
#define IDB_BITMAP_DOWN0                233
#define IDB_BITMAP_DISCONNECT           234
#define IDB_BITMAP_DISCUT               235
#define IDB_BITMAP_DISCON               236
#define IDB_BITMAP_WEWINS               237
#define IDB_BITMAP_CALLDOWN             243
#define IDB_BITMAP_HANGUPDOWN           244
#define IDB_BITMAP_LOGIN                248
#define IDB_BITMAP_PRESS                249
#define IDB_BITMAP_OUTLOOK              250
#define IDD_DIALOG_SEL_SP               251
#define IDD_DIALOG_REMOVE_PROMPT        269
#define IDD_DIALOG_REPEAT               270
#define IDD_DIALOG_IMPORT_REPEAT        273
#define IDD_DIALOG_UPDATE               274
#define IDD_DIALOG_UPDATEPROGRESS       275
#define IDD_DIALOG_FLUXSTAT             276
#define IDR_MENU_CH                     278
#define IDR_MENU_CN                     278
#define IDD_DIALOG_IPDNS                279
#define IDB_BITMAP_COMBOOVER            282
#define IDB_BITMAP_COMBODOWN            283
#define IDB_BITMAP_COMBONO              284
#define IDD_DIALOG_PIN                  293
#define IDD_DIALOG2                     294
#define IDD_DIALOG_PINOPER              295
#define IDB_BITMAP13                    297
#define IDB_BITMAP14                    299
#define IDB_BITMAP15                    300
#define IDS_CDROM_REINSTALL             301
#define IDD_DIALOG_SELNETWORK           301
#define IDR_IMPORT_PIN                  302
#define IDR_PIN_OPERATION               303
#define IDS_WCDMA_MODEM                 304
#define IDB_BITMAP_SELNETWORK           306
#define IDB_BITMAP_RERESH               308
#define IDB_BITMAP_REFRESH              308
#define IDB_BITMAP_NREFRESH             310
#define IDB_BITMAP_NREGISTER            311
#define IDD_DIALOG_COPS                 312
#define IDB_BITMAP_WAITCOPS             314
#define IDB_BITMAP_COPSRE               316
#define IDD_DIALOG_COPSRE               317
#define IDB_BITMAP_GRAY                 318
#define IDB_BITMAP_BLUE                 319
#define IDD_DIALOG_APN                  337
#define IDS_REGISTER                    499
#define IDS_REFRESH                     500
#define IDS_MOVE_1                      501
#define IDS_MOVE_2                      502
#define IDS_MOVE_3                      503
#define IDS_INPUT_NAME                  504
#define IDS_INPUT_CLASS                 505
#define IDS_DEL_INFO                    506
#define IDS_NO_SIM_CARD                 507
#define IDS_NO_SC700_CARD               508
#define IDS_NEW_SMS                     510
#define IDS_EDIT_SMS                    511
#define IDS_NEW_CARD                    512
#define IDS_EDIT_CARD                   513
#define IDS_NEW_CLASS                   514
#define IDS_EDIT_CLASS                  515
#define IDS_EXIT_CONPROCESS             516
#define IDS_RASCON_PROMPT               517
#define IDS_REPEAT_NOTICE               518
#define IDS_PREPARE_NETCONNECT          519
#define IDS_DELCARD_INLIST              520
#define IDS_QUERYCONDITON_NOTEMPTY      521
#define IDS_STARTGREAT_ENDTIME          523
#define IDS_INPUTCARD_INFORMATION       524
#define IDS_NOT_DIALMULTINUM            525
#define IDS_IMPORT_OPENFILEFAIL         526
#define IDS_IMPORT_CANCEL               527
#define IDS_IMPORT_EMPTY                528
#define IDS_IMPORT_FAIL                 529
#define IDS_EXPORT_CARD                 530
#define IDS_CARD_EXPORTING              531
#define IDS_EXPORT_CANCEL               532
#define IDS_OPENOE_FAIL                 533
#define IDS_SYN_PROGRESS                534
#define IDS_SYNFROMOE_NOW               535
#define IDS_CONTACTS_ISNULL             536
#define IDS_SYN_FAIL                    537
#define IDS_OPENOO_FAIL                 538
#define IDS_SYN_HASCANCEL               539
#define IDS_SYNTO_OE                    540
#define IDS_GETCONTACTITEM_FAIL         541
#define IDD_ABOUTBOX                    600
#define IDD_SUNNYCAT_DIALOG             601
#define IDR_MAINFRAME                   602
#define IDR_MENU                        603
#define IDD_DIALOG_NETWORK              604
#define IDD_NEWCLASS_DLG                605
#define IDD_DIALOG_CALL                 606
#define IDD_DIALOG_SMS                  607
#define IDB_CARDICON                    608
#define IDR_SMS_RKEYDOWN                609
#define IDR_MENU_SMS                    610
#define IDD_DIALOG_NEW_SMS              611
#define IDB_BITMAP_EXIT                 612
#define IDB_BITMAP_EXITOVER             613
#define IDD_DIALOG_LINKMAN              614
#define IDD_DIALOG_RECORD               615
#define IDD_DIALOG_OTHER                616
#define IDB_BITMAP_VOLBK                617
#define IDB_BITMAP_VOLBTN               618
#define IDR_MENU_RECORD                 619
#define IDD_DIALOG_SMSSELECTCARD        620
#define IDD_DIALOG_SELECTCLASS          621
#define IDR_MENU_LINKMAN                622
#define IDD_NEWCARD_DLG                 623
#define IDD_DIALOG_SYSSET               624
#define IDB_BITMAP_DIAL                 625
#define IDB_BITMAP_DIALDOWN             626
#define IDD_DIALOG_SETCONNECT           627
#define IDD_DIALOG_SET                  628
#define IDB_BITMAP_LOGO                 629
#define IDB_BITMAP_S5                   630
#define IDB_BITMAP_S0                   631
#define IDB_BITMAP_S1                   632
#define IDB_BITMAP_S2                   633
#define IDB_BITMAP_S3                   634
#define IDB_BITMAP_S4                   635
#define IDB_BITMAP_EGDG                 636
#define IDB_BITMAP_NEWSMS               637
#define IDB_BITMAP_ROAMING              638
#define IDB_BITMAP_NOTREGISTER          639
#define IDB_BITMAP_REGISTER             639
#define IDB_BITMAP_REGSUCCEESS          640
#define IDB_BITMAP_GSM                  641
#define IDB_BITMAP_EDGE                 642
#define IDB_BITMAP_GPRS                 643
#define IDD_PROGRESS                    644
#define IDD_DIALOG_SETRING              645
#define IDD_DIALOG_TURNCALL             646
#define IDS_SMS_CENTER                  700
#define IDS_SMS_RECVBOX                 701
#define IDS_SMS_SENDBOX                 702
#define IDS_SMS_UNSENDBOX               703
#define IDS_SMS_DRAFBOX                 704
#define IDS_SMS_RECYBOX                 705
#define IDS_SMS_SIMBOX                  706
#define IDS_SMS_REVERT                  707
#define IDS_SMS_TURNSEND                708
#define IDS_SMS_SEND                    709
#define IDS_SMS_RESEND                  710
#define IDS_SMS_NEWSMS                  711
#define IDS_SMS_LISTHEAD                712
#define IDS_SMS_SMSCONTENT              713
#define IDS_LINKMAN_LISTHEAD            740
#define IDS_LINKMAN_PC                  741
#define IDS_LINKMAN_NOCLASS             742
#define IDS_LINKMAN_QUERY               743
#define IDS_LINKMAN_QUERYZERO           744
#define IDS_LINKMAN_SIM                 745
#define IDS_LINKMAN_NEWCARD             746
#define IDS_LINKMAN_DEL                 747
#define IDS_LINKMAN_CLEAR               748
#define IDS_LINKMAN_SEARCH              749
#define IDS_LINKMAN_SIMZERO             750
#define IDS_LINKMAN_DIAL                751
#define IDS_LINKMAN_INPUTNOTICE         752
#define IDS_LINKMAN_ISCLEAR             753
#define IDS_LINKMAN_QUERYNOTICE         754
#define IDS_LINKMAN_NOTICE              755
#define IDS_RECORD_LISTHEAD_CALL        756
#define IDS_RECORD_LISTHEAD_NETALL      757
#define IDS_RECORD_LISTHEAD_NETMON      758
#define IDS_RECORD_LISTHEAD_NETTIME     759
#define IDS_RECORD_CALL                 760
#define IDS_RECORD_RECV                 761
#define IDS_RECORD_DAIL                 762
#define IDS_RECORD_MISS                 763
#define IDS_RECORD_NET                  764
#define IDS_RECORD_NETALL               765
#define IDS_RECORD_NETMON               766
#define IDS_RECORD_NETTIME              767
#define IDS_CALL_CLEAR                  768
#define IDS_CALL_DAIL                   769
#define IDS_CALL_HANGUP                 770
#define IDS_SUNNYCAT_CONNECT            771
#define IDS_SUNNYCAT_UNCONNECT          772
#define IDS_SUNNYCAT_SENDOK             773
#define IDS_SUNNYCAT_SENDFAIL           774
#define IDS_CONNECT_FAIL                775
#define IDS_OUTPUT_INFO                 776
#define IDS_INPUT_INFO                  777
#define IDS_MSGBOX_OK                   778
#define IDS_MSGBOX_CANCEL               779
#define IDS_MSGBOX_EXIT                 780
#define IDS_MSGBOX_RETRY                781
#define IDS_MSGBOX_IGNO                 782
#define IDS_MSGBOX_YES                  783
#define IDS_MSGBOX_NO                   784
#define IDS_MSGBOX_CLOSE                785
#define IDS_MSGBOX_HELP                 786
#define IDS_MSGBOX_YESALL               787
#define IDS_MSGBOX_NOALL                788
#define IDS_SMS_INALL                   789
#define IDS_SMS_SUM                     790
#define IDS_SEL_LINKMAN_LISTHEADA       791
#define IDS_SEL_LINKMAN_LISTHEADB       792
#define IDS_SEL_LINKMAN_SUM             793
#define IDS_OUTLOOK_HEADSHIP            794
#define IDS_OUTLOOK_MAIL                795
#define IDS_OUTLOOK_COUNTRY             796
#define IDS_OUTLOOK_HOME                797
#define IDS_OUTLOOK_FAX                 798
#define IDS_OUTLOOK_COMPANY             799
#define IDS_OUTLOOK_OFFICE              800
#define IDS_OUTLOOK_NAME                801
#define IDS_OUTLOOK_MOBPHONE            802
#define IDS_OUTLOOK_CLASS               803
#define IDS_CLASS_NOCLASS               804
#define IDS_OUTLOOK_REPEAT_A            805
#define IDS_OUTLOOK_REPEAT_B            806
#define IDS_OUTLOOK_INFO_A              807
#define IDS_OUTLOOK_INFO_B              808
#define IDS_OUTLOOK_INFO_C              809
#define IDS_OUTLOOK_INFO_D              810
#define IDS_OUTLOOK_INFO_E              811
#define IDS_OUTLOOK_INFO_F              812
#define IDS_OUTPUT_A                    813
#define IDS_OUTPUT_B                    814
#define IDS_OUTPUT_FAIL                 815
#define IDS_SAMESTEP_A                  816
#define IDS_SAMESTEP_B                  817
#define IDS_SAMESTEP_C                  818
#define IDS_SAMESTEP_D                  819
#define IDS_SAMESTEP_E                  820
#define IDS_SAMESTEP                    821
#define IDS_SAMESTEP_TIMES              822
#define IDS_TRY_SAMESTEP_A              823
#define IDS_TRY_SAMESTEP_B              824
#define IDS_TRY_SAMESTEP_C              825
#define IDS_SIM_LOCK_ERROR              826
#define DOWNLOAD_FAIL                   827
#define VERSION_ERROR                   828
#define DOWLOADFILE_ERROR               829
#define IDS_UPDATE_TITLE                830
#define IDS_UPDATE_CAPTION              831
#define IDS_UPDATE_CONFIRM              832
#define IDS_UPDATE_SETUP                833
#define IDS_UPDATE_CONFIRMEXIT          834
#define IDS_UPDATE_PERCENT              835
#define IDS_SYNTO_OO_PROGRESS           836
#define IDS_FLUX_WARN                   837
#define IDS_FLUX_WARNTITLE              838
#define IDS_FLUX_UNCNT                  839
#define IDS_FLUX_UNCNTTITLE             840
#define IDS_FLUX_ERRORSET               841
#define IDS_FLUX_ERRORSETTITLE          842
#define IDS_FLUX_NOTSET                 843
#define IDS_FLUX_SET                    844
#define IDS_SP_LIST_NUM                 845
#define IDS_SP_LIST_NAME                846
#define IDS_SP_STATE                    847
#define IDS_SP_REG_OK                   848
#define IDS_SP_REG_FAIL                 849
#define IDS_SP_NOTICE                   850
#define IDS_SP_WAIT                     851
#define IDS_SP_SEARCH                   852
#define IDS_SP_REG_UNABLE               853
#define IDS_SP_REG_CURRENT              854
#define IDS_UPDATE_URL                  855
#define IDS_FLUX_UNCNTPROMPT            856
#define IDS_FLUX_NOTSETPROMPT           857
#define IDS_FLUX_SETPROMPT              858
#define IDS_IMPORT_FILE_EMPTY           859
#define IDS_COPYREGHT                   860
#define IDS_ABOUT_TEXT                  861
#define IDS_OK                          862
#define IDS_CHECK_REPEAT                863
#define IDS_YES                         864
#define IDS_NO                          865
#define IDS_REPEAT_TEXT                 866
#define IDS_SMS_CHANG                   867
#define IDS_SMS_SAVE                    868
#define IDS_SMS_OTHER                   869
#define IDS_SMS_DAIL                    870
#define IDS_SMS_DEL                     871
#define IDS_SMS_ALL                     872
#define IDS_SMS_COPY                    873
#define IDS_SMS_RECVALL                 874
#define IDS_SMS_RECV                    875
#define IDS_MENU_CONNECT                876
#define IDS_MENU_UNCONNECT              877
#define IDS_MENU_SET                    878
#define IDS_MENU_CLOSE                  879
#define IDS_MENU_ADDLINKMAN             880
#define IDS_LINKMAN_OUTPUT              881
#define IDS_LINKMAN_INPUT               882
#define IDS_SYN_FROM_OUTLOOK            883
#define IDS_SYN_TO_OUTLOOK              884
#define IDS_SYN_FROM_OO                 885
#define IDS_SYN_TO_OO                   886
#define IDS_AUTO_UPDATE                 887
#define IDS_MENU_HELPINFO               888
#define IDS_MENU_ABOUT                  889
#define IDS_CLEAR                       890
#define IDS_RECORD_SMS                  891
#define IDS_LINKMAN_EDITCARD            892
#define IDS_LINKMAN_NEWCLASS            893
#define IDS_NEWCARD                     894
#define IDS_LINKMAN_SSMS                895
#define IDS_LINKMAN_EDITCLASS           896
#define IDS_LINKMAN_DELCLASS            897
#define IDS_LINKMAN_CLEARCARD           898
#define IDS_NET_COUNT                   899
#define IDS_START_TIME                  900
#define IDS_END_TIME                    901
#define IDS_STATIC_RECV                 902
#define IDS_STATIC_SEND                 903
#define IDS_SAVE_SMS                    904
#define IDS_SEND_SMS                    905
#define IDS_SMS_RECEIVER                906
#define IDS_RECEIVER                    907
#define IDS_SMS_NOTICE                  908
#define IDS_SMS_CONTENT                 909
#define IDS_SIM_CARD                    910
#define IDS_SIM_NAME                    911
#define IDS_SIM_NUM                     912
#define IDS_REMOVE_PROMPT               913
#define IDS_REPEAT_DLG                  914
#define IDS_YES_ALL                     915
#define IDS_NO_ALL                      916
#define IDS_SEL_CLASS                   917
#define IDS_SETTING                     918
#define IDS_DIAL_INFO                   919
#define IDS_USER_NAME                   920
#define IDS_USER_PASSWORD               921
#define IDS_USER_PHONE                  922
#define IDS_CONNECT_POINT               923
#define IDS_SELECT_NETWORK              924
#define IDS_CURRENT_NETWORK             925
#define IDS_BUTTON_SET                  926
#define IDS_BUTTON_SEARCH               927
#define IDS_COMING_TONE                 928
#define IDS_SMS_TONE                    929
#define IDS_WRITE_SMS                   930
#define IDS_REPLY_SMS                   931
#define IDS_FORWARD_SMS                 932
#define IDS_SEARCH_CONTENT              933
#define IDS_RECEIVER_LIST               934
#define IDS_ADD                         935
#define IDS_ADD_ALL                     936
#define IDS_REMOVE                      937
#define IDS_REMOVE_ALL                  938
#define IDS_SELECT_COUNT                939
#define IDS_SYSSET_AUTO                 940
#define IDS_SYSSET_MIN                  941
#define IDS_SYSSET_SHOW                 942
#define IDS_SYSSET_UPDATE               943
#define IDS_COMMUNITCATION              944
#define IDS_SELECT_CLASS                945
#define IDS_CARD_NAME                   946
#define IDS_HOME_NUM                    947
#define IDS_FAX_NUM                     948
#define IDS_MOBILE_NUM                  949
#define IDS_OFFICE_NUM                  950
#define IDS_ADDRESS_INFO                951
#define IDS_COUNTRY                     952
#define IDS_COMPANY                     953
#define IDS_HEADSHIP                    954
#define IDS_BUTTON_SELECT               955
#define IDS_CLASS_NAME                  956
#define IDS_RING_PATH                   957
#define IDS_FILE                        958
#define IDS_CONTACT                     959
#define IDS_HELP                        960
#define IDS_SELECT_CARD                 962
#define IDS_MACH5URL                    963
#define IDS_DEFAULT_SET                 964
#define IDS_INPUT_CLASSNAME             965
#define IDS_SEL_COM                     966
#define IDS_NO_DATABASE                 967
#define IDS_UPLOADSPEED                 968
#define IDS_DOWNLOADSPEED               969
#define IDS_CURRENTLINKINFO             970
#define IDS_LINKTIME                    971
#define IDS_UPLOAD                      972
#define IDS_DOWNLOAD                    973
#define IDS_SPEED                       974
#define IDS_FLUX                        975
#define IDS_STATISTICS                  976
#define IDS_TIMELAST                    977
#define IDS_DAY                         978
#define IDS_MONTH                       979
#define IDS_YEAR                        980
#define IDS_UPLOADDATA                  981
#define IDS_DOWNLOADDATA                982
#define IDS_CONNECT                     983
#define IDS_DISCONNECT                  984
#define IDS_RESETSTATISTICS             985
#define IDS_EXPANDALL                   986
#define IDS_COLLAPSEALL                 987
#define IDS_PAINTSPEED                  988
#define IDS_LINK                        989
#define IDS_STAT                        990
#define IDS_CALL                        991
#define IDS_SMS                         992
#define IDS_PB                          993
#define IDS_SAVENUM                     994
#define IDS_VOICE                       995
#define IDS_VOICEOUT                    996
#define IDS_VOICEPC                     997
#define IDS_IS_SAVE                     998
#define IDS_NEW_CARD_FAIL               999
#define IDS_EDIT_CARD_FAIL              1000
#define IDC_TAB                         1000
#define IDS_VOICE_SWITCH                1001
#define IDC_BUTTON_SMS                  1001
#define IDS_NOTINSTALL_PDF              1002
#define IDC_BUTTON_DIAL                 1002
#define IDS_SIM_LOCK                    1003
#define IDC_BUTTON_HANGUP               1003
#define IDS_SIMREAD_RESULT              1004
#define IDS_INIT_RUNNING                1005
#define IDS_SEARCH_NET                  1006
#define IDS_PB_FULL                     1007
#define IDC_TREE_SMS                    1010
#define IDC_LIST_SMS                    1011
#define IDC_BUTTON_NEWSMS               1013
#define IDC_BUTTON_REVERT               1014
#define IDC_BUTTON_TRANSMIT             1015
#define IDC_BUTTON_DEL                  1016
#define IDC_BUTTON_CLEAR                1017
#define IDC_LIST_SHOWSMS                1018
#define IDC_TREE_SEL                    1018
#define IDC_EDIT_SHOW                   1019
#define IDC_EDIT_SP_RING                1019
#define IDC_STATIC_SMSCLASS             1020
#define IDC_EDIT_SMS_NUM                1021
#define IDC_BUTTON_SEL_LINKMAN          1022
#define IDC_EDIT_SMS_CONTENT            1023
#define IDC_BUTTON_SMS_SAVE             1024
#define IDC_BUTTON_SEND                 1025
#define IDC_STATIC_CLASSNAME            1026
#define IDC_STATIC_SMS_INFO             1027
#define IDC_STATIC_CLASS_RING           1027
#define IDC_BUTTON_2                    1028
#define IDC_BUTTON_3                    1029
#define IDC_BUTTON_5                    1030
#define IDC_BUTTON_6                    1031
#define IDC_STATIC_GROUP_PHONEINFO      1031
#define IDC_STATIC_ADDRESS              1031
#define IDC_BUTTON_8                    1032
#define IDC_STATIC_CLASS                1032
#define IDC_STATIC_GROUP_PHONEINFO2     1032
#define IDC_STATIC_COMMICATION          1032
#define IDC_BUTTON_4                    1033
#define IDC_STATIC_CARDNAME             1033
#define IDC_BUTTON_1                    1034
#define IDC_BUTTON_7                    1035
#define IDC_STATIC_GROUP_ADDRESS        1035
#define IDC_BUTTON_9                    1036
#define IDC_STATIC_GROUP_REMARK         1036
#define IDC_BUTTON_10                   1037
#define IDC_EDIT_CLASSNAME              1037
#define IDC_BUTTON_11                   1038
#define IDC_EDIT_NAME                   1038
#define IDC_EDIT_DAIL_NUM               1039
#define IDC_STATIC_COMPANYNAME          1039
#define IDC_BUTTON_0                    1040
#define IDC_BUTTON1                     1040
#define IDC_BUTTON_RECORD_DEL           1040
#define IDC_EDIT_MEMO                   1040
#define IDC_EDIT_MOBILEPHONE            1040
#define IDC_BUTTON_EXIT                 1040
#define IDC_BUTTON_SEL_SP               1040
#define IDC_BUTTON_SET_SP               1040
#define IDC_BUTTON_ADVANCED             1040
#define IDC_BUTTON_LINK                 1040
#define IDC_BUTTON_CONNECTEVDO          1040
#define IDC_BUTTON_SNREFRESH            1040
#define IDC_BUTTON_COPS                 1040
#define IDC_BUTTON2                     1041
#define IDC_BUTTON_DIAL_CLEAR           1041
#define IDC_BUTTON_RECORD_CLEAR         1041
#define IDC_STATIC_HEADSHIP             1041
#define IDC_MENU_SETLINKMAN             1041
#define IDC_BUTTON_SETCALLRING          1041
#define IDC_BUTTON_ALL_NO               1041
#define IDC_BUTTON_SEARCH_SP            1041
#define IDC_BUTTON_CONNECT1X            1041
#define IDC_BUTTON_SNREGISTER           1041
#define IDC_BUTTON_REDIAL               1042
#define IDC_STATIC_COMPANYADDRESS       1042
#define IDC_BUTTON_SELRING              1042
#define IDC_MENU_HELP                   1042
#define IDC_EDIT_HOMEPHONE              1042
#define IDC_BUTTON_UNCONNECTEVDO        1042
#define IDC_EDIT_CARDPATH               1043
#define IDC_MENU_ACCELERATE             1043
#define IDC_MENU_HELP2                  1043
#define IDC_BUTTON_DIAL_NUM             1044
#define IDC_EDIT_OFFICEPHONE            1044
#define IDC_MENU_OPERATION              1044
#define IDC_BUTTON_SELCARDCLS           1045
#define IDC_LIST_SHOW_RECORD            1046
#define IDC_BUTTON_QUERY_LINKMAN        1046
#define IDC_EDIT_FAXPHONE               1046
#define IDC_TREE_RECORD                 1047
#define IDC_EDIT_MSNACCOUNT             1047
#define IDC_LIST_RECORD                 1048
#define IDC_EDIT_MOBILE1                1048
#define IDC_TREE_LINKMAN                1049
#define IDC_EDIT_QQNUMBER               1049
#define IDC_LIST_LINKMAN                1050
#define IDC_LIST_SHOW_LINKMAN           1051
#define IDC_EDIT_SKYPE                  1051
#define IDC_BUTTON_NEW_LINKMAN          1052
#define IDC_EDIT_OFFICE1                1052
#define IDC_BUTTON_NEWCLASS_LINKMAN     1053
#define IDC_EDIT_EMAIL                  1053
#define IDC_BUTTON_CLEAR_LINKMAN        1054
#define IDC_BUTTON_DEL_LINKMAN          1055
#define IDC_EDIT_QUERY_LINKMAN          1056
#define IDC_BUTTON_EDIT_LINKMAN         1057
#define IDC_EDIT_FAXNUM                 1057
#define IDC_STATIC_SOUND                1058
#define IDC_EDIT_HOMELINE               1058
#define IDC_EDIT_COMADDRESS             1060
#define IDC_MENU_FILE                   1061
#define IDC_EDIT_HEADSHIP               1062
#define IDC_COMBO1                      1063
#define IDC_EDIT_HEADSHIP2              1063
#define IDC_COMBO_APN                   1063
#define IDC_COMBO_COM                   1063
#define IDC_BUTTON_CONNECT              1064
#define IDC_TREE_SEL_LINKMAN            1065
#define IDC_BUTTON_UNCONNECT            1065
#define IDC_EDIT_COURTRY                1065
#define IDC_LIST1                       1066
#define IDC_LIST_SEL                    1066
#define IDC_EDIT_COMPANY                1066
#define IDC_LIST_SP                     1066
#define IDC_LIST_SP_NAME                1066
#define IDC_CHECK_AUTO                  1068
#define IDC_CHECK_MIN                   1069
#define IDC_CHECK_TOP                   1070
#define IDC_CHECK_SHOWWND               1071
#define IDC_TAB_SET                     1072
#define IDC_BUTTON_RENEW                1073
#define IDC_EDIT1                       1074
#define IDC_EDIT_CALLRING               1074
#define IDC_EDIT_SELCLASS               1074
#define IDC_EDIT_SP_NAME                1074
#define IDC_EDIT_UPLIMIT                1074
#define IDC_EDIT_NMUNCNT                1074
#define IDC_EDIT_PSW                    1075
#define IDC_EDIT2                       1075
#define IDC_EDIT_SMSRING                1075
#define IDC_EDIT_PERCENT                1075
#define IDC_EDIT_NMWARN                 1075
#define IDC_BUTTON_SETSMSRING           1076
#define IDC_STATIC_S0                   1077
#define IDC_STATIC_S1                   1078
#define IDC_STATIC_S2                   1079
#define IDC_STATIC_S3                   1080
#define IDC_STATIC_S4                   1081
#define IDC_STATIC_S5                   1082
#define IDC_STATIC_EDGE                 1083
#define IDC_STATIC_SMSIMG               1084
#define IDC_STATIC_ROAMING              1085
#define IDC_STATIC_NOTREG               1086
#define IDC_STATIC_REG                  1087
#define IDC_STATIC_GSM                  1088
#define IDC_STATIC_EG                   1089
#define IDC_EDIT_SMSSEARCHTXT           1090
#define IDC_STATIC_GPRS                 1090
#define IDC_STATIC_INFOBAR              1091
#define IDC_STATIC_XX                   1092
#define IDC_STATIC_ICON7                1092
#define IDC_CONNECT_ONSTARTUP           1093
#define IDC_AUTO_RECONNECT              1094
#define IDC_BUTTON3                     1095
#define IDC_BUTTON_SELCLASS             1095
#define IDC_BUTTON_NEW                  1095
#define IDC_BUTTON_CALL                 1095
#define IDC_BUTTON_ADDNUM               1095
#define IDC_EDIT_NAME_SIM               1096
#define IDC_BUTTON_EDIT                 1096
#define IDC_EDIT_NUM_SIM                1097
#define IDC_BUTTON_DELETE               1097
#define IDC_BUTTON_14                   1097
#define IDC_DATETIMEPICKER_START        1098
#define IDC_STATIC_SEND                 1098
#define IDC_BUTTON_13                   1098
#define IDC_DATETIMEPICKER_END          1099
#define IDC_STATIC_CONTENT              1100
#define IDC_STATIC_SEL                  1101
#define IDC_EDIT_PHONENUM               1102
#define IDC_EDIT_APN                    1103
#define IDC_STATIC_LINEBOTTOM           1103
#define IDC_STATIC_LINETOP              1105
#define IDC_SPLITTER1                   1106
#define IDC_SPLITTER2                   1107
#define IDC_SPLITTER3                   1108
#define IDC_BUTTON4                     1108
#define IDC_BUTTON_RECORD               1108
#define IDC_STATIC_CALLIN               1110
#define IDC_STATIC_CALLIN0              1111
#define IDC_STATIC_CALLIN2              1112
#define IDC_STATIC_WEWINS               1113
#define IDC_STATIC_REMOVE_CARD          1113
#define IDC_STATIC_CALLIN4              1114
#define IDC_BUTTON_ALL_OK               1114
#define IDC_PROGRESS                    1115
#define IDC_STATIC_REPEAT               1115
#define IDC_STATIC_CALLIN3              1116
#define IDC_MSCHART                     1116
#define IDC_STATIC_CALLIN7              1117
#define IDC_MSCHART_SEND                1117
#define IDC_STATIC_CALLIN1              1118
#define IDC_STATIC_CALLIN5              1119
#define IDC_STATIC_SEND_RATE            1119
#define IDC_STATIC_CALLIN6              1120
#define IDC_STATIC_RECV_RATE            1120
#define IDC_SEND_RATE                   1122
#define IDC_BUSY_PHONE                  1124
#define IDC_RECV_RATE                   1124
#define IDC_NOANSWER_PHONE              1125
#define IDC_RECV_TOTAL                  1125
#define IDC_NOCONDITION_PHONE           1126
#define IDC_CHECK_APP_ALL               1126
#define IDC_NOTREACHABLE_PHONE          1127
#define IDC_STATIC_REPEAT_PROMPT        1127
#define IDC_STATIC_SELCLASS             1128
#define IDC_STATIC_COUNTRY              1129
#define IDC_STATIC_PHOTO                1130
#define IDC_STATIC_NOTICE               1130
#define IDC_PROGRESS_UPDATE             1131
#define IDC_STATIC_START                1131
#define IDC_STATIC_PERCENT              1132
#define IDC_STATIC_END                  1132
#define IDC_BUTTON_SMSSEARCH            1133
#define IDC_CHECK_AUTOUPDATE            1133
#define IDC_STATIC_RECEIVER             1133
#define IDC_CHECK_YN                    1134
#define IDC_SMS_NOTICE                  1134
#define IDC_STATIC_SMS_CONTENT          1135
#define IDC_LIST_FORSEL                 1136
#define IDC_SPIN_UPLIMIT                1136
#define IDC_SPIN_UNCNT                  1136
#define IDC_SIM_NAME                    1136
#define IDC_SIM_PHONE                   1137
#define IDC_BUTTON_ADDTOSEL             1138
#define IDC_SPIN_PERCENT                1138
#define IDC_SPIN_WARN                   1138
#define IDC_SEL_NETWORK                 1138
#define IDC_BUTTON_ADDALLTOSEL          1139
#define IDC_CURRENT_NET                 1139
#define IDC_BUTTON_REMOVE               1140
#define IDC_COMING_TONE                 1140
#define IDC_BUTTON_REMOVEALL            1141
#define IDC_SMS_TONE                    1141
#define IDC_IPADDRESS_DNS2              1142
#define IDC_EDIT_NM                     1142
#define IDC_SEARCH_CONTENT              1142
#define IDC_IPADDRESS_DNS1              1143
#define IDC_SPIN_NM                     1143
#define IDC_RECEIVER_LIST               1143
#define IDC_CHECK_DNS                   1144
#define IDC_SELECT_COUNT                1144
#define IDC_EDIT_USER                   1145
#define IDC_STATIC_SEL_COM              1145
#define IDC_EDIT_PASSWORD               1146
#define IDC_EDIT_DATE                   1146
#define IDC_RADIO_UMODEM                1146
#define IDC_IPADDRESS_STATIC_IP         1147
#define IDC_SPIN_DATE                   1147
#define IDC_RADIO_UDISK                 1147
#define IDC_STATIC_FORSELINFO           1148
#define IDC_IPADDRESS_IP                1150
#define IDC_STATIC_IP                   1152
#define IDC_STATIC_DNS1                 1153
#define IDC_STATIC_DNS2                 1154
#define IDC_CHECK_DLGCHECK              1155
#define IDC_RADIO_AUTOIP                1155
#define IDC_CHECK_WARNUNCNT             1156
#define IDC_RADIO_STATICIP              1156
#define IDC_STATIC_1                    1157
#define IDC_RADIO_AUTODNS               1157
#define IDC_STATIC_2                    1158
#define IDC_RADIO_STATICDNS             1158
#define IDC_STATIC_3                    1159
#define IDC_BUTTON_LINKMAN              1159
#define IDC_STATIC_4                    1160
#define IDC_BUTTON_NET                  1160
#define IDC_PROGRESS_INFO               1161
#define IDC_STATIC_5                    1161
#define IDC_STATIC_LINE1                1161
#define IDC_PROGRESS_BAR                1162
#define IDC_STATIC_LINE2                1162
#define IDC_STATIC_7                    1163
#define IDC_STATIC_LINE3                1163
#define IDC_STATIC_NOTONLINE            1164
#define IDC_STATIC_9                    1165
#define IDC_TREE_NET                    1165
#define IDC_STATIC_6                    1166
#define IDC_RADIO_VOICEOUT              1166
#define IDC_CHECK_UNCNT                 1167
#define IDC_RADIO_VOICEPC               1167
#define IDC_STATIC_8                    1168
#define IDC_STATIC_VOICE                1168
#define IDC_STATIC_EAR                  1169
#define IDC_STATIC_EVDO                 1170
#define IDC_EDIT_PHONE                  1171
#define IDC_APPNAME                     1171
#define IDC_STATIC_ICON0                1171
#define IDC_COPYRIGHT                   1172
#define IDC_STATIC_USER                 1172
#define IDC_STATIC_ICON1                1172
#define IDC_STATIC_PSW                  1173
#define IDC_STATIC_ICON2                1173
#define IDC_STATIC_PHONE                1174
#define IDC_STATIC_ICON3                1174
#define IDC_STATIC_ICON4                1175
#define IDC_STATIC_ICON5                1176
#define IDC_STATIC_1X                   1177
#define IDC_STATIC_PINNAME              1178
#define IDC_STATIC_CONNECT_INFO         1179
#define IDC_EDIT_PINCODE                1179
#define IDC_STATIC_USERNAME             1180
#define IDC_PINOPER_REMAINING           1180
#define IDC_STATIC_PASSWORD             1181
#define IDC_EDIT_PINOPERCODE            1181
#define IDC_STATIC_PHONENUM             1182
#define IDC_TEXT_PINOPERCODE            1182
#define IDC_STATIC_MAINDNS              1183
#define IDC_STATIC_SECONDDNS            1184
#define IDC_STATIC_APN                  1185
#define IDC_CHECK_MANUAL                1186
#define IDC_LIST_NETWORK                1189
#define IDS_NETWORK_LISTHEAD            1190
#define IDC_STATIC_REGISTER             1194
#define IDC_STATIC_COPS_REGISTER        1195
#define IDC_CHECK_STATIC_IP             1230
#define IDC_STATIC_IP_ADDRESS           1232
#define IDC_ACTIVE                      1236
#define IDC_CFBUSY                      1239
#define IDC_CFNOANSWER                  1240
#define IDC_CFNOCONDITION               1241
#define IDC_CFNOTREACHABLE              1242
#define IDC_RADIO_CANCEL                1247
#define IDC_STATIC_PHNUM1               1348
#define IDC_STATIC_PHNUM2               1349
#define IDC_STATIC_MOBPHONE             1349
#define IDC_STATIC_PHNUM3               1350
#define IDC_STATIC_OFFICE               1350
#define IDC_STATIC_PHNUM6               1353
#define IDC_STATIC_FAX                  1353
#define IDC_STATIC_PHNUM7               1354
#define IDC_STATIC_HOME                 1354
#define IDC_EDIT_MSGTXT                 1356
#define IDM_START                       1500
#define IDM_END                         1504
#define IDS_WAITFORDELETE               1505
#define IDS_DELETEPBCANCEL              1506
#define IDS_WAITFORMOVEPB               1507
#define IDS_MOVEPBCANCEL                1508
#define IDS_NEWCLASSEXIST               1509
#define IDR_PINOPERATION_ENABLE         1510
#define IDR_PINOPERATION_DISABLE        1511
#define IDS_PINENABLE                   1512
#define IDS_PINDISABLE                  1513
#define IDS_MENU_SELNETWORK             1514
#define IDS_REGISTER_OK                 1515
#define IDS_REGISTER_AUTO               1517
#define IDS_REGISTER_MANUAL             1518
#define IDS_NETWORK_SELECT              1519
#define IDS_WAIT_COPS                   1520
#define IDS_PROMPT                      1521
#define IDS_REGISTER_NETWORK            1522
#define IDS_REGISTER_FAILTURE           1523
#define IDS_REGISTER_SUCCESS            1524
#define IDS_PC                          1525
#define IDS_HOME                        1526
#define IDS_FRIEND                      1527
#define IDS_BUSINESS                    1528
#define IDS_OTHERS                      1529
#define IDS_FINISH_COPS                 1530
#define IDS_FINISH_REGISTER             1531
#define IDM_NETTREE_CLEAR               32600
#define IDM_NETTREE_EXPAND              32601
#define IDM_NETTREE_COLLAPSE            32602
#define IDM_OPREATION_LINK              32603
#define IDM_OPERATION_NETWORK           32604
#define IDM_OPERATION_CALL              32605
#define IDM_OPERATION_SMS               32606
#define IDM_OPERATION_PB                32607
#define IDR_NEW                         32771
#define IDR_MENU_CONNECT                32771
#define IDR_SET_NET                     32772
#define IDR_NEWMSG                      32774
#define IDR_REVERT_SMS                  32775
#define IDR_SMS_REVERT                  32775
#define IDR_CHANG_SMS                   32776
#define IDR_SMS_CHANG                   32776
#define IDR_DAIL                        32777
#define IDR_SMS_DAIL                    32777
#define IDR_DEL                         32778
#define IDR_SMS_DEL                     32778
#define IDR_CLEAR                       32779
#define IDR_SEL_ALL                     32780
#define IDR_SMS_ALL                     32780
#define IDR_SEL_OTHER                   32781
#define IDR_SMS_OTHER                   32781
#define IDR_SAVE_NUM                    32784
#define IDR_SMS_SAVE                    32784
#define IDR_RECORD_SMS                  32786
#define IDR_RECORD_DIAL                 32787
#define IDR_RECORD_DEL                  32788
#define IDR_RECORD_CLEAR                32789
#define IDR_RECORD_SAVE                 32790
#define IDR_RECORD_ALL                  32791
#define IDR_RECORD_OTHER                32792
#define IDR_LINKMAN_NEWCLASS            32793
#define IDR_LINKMAN_NEWCARD             32794
#define IDR_LINKMAN_SSMS                32795
#define IDR_LINKMAN_CLEARCARD           32797
#define IDR_LINKMAN_EDITCLASS           32798
#define IDR_LINKMAN_DELCLASS            32799
#define IDR_LINKMAN_SMS                 32800
#define IDR_LINKMAN_DIAL                32801
#define IDR_LINKMAN_DEL                 32802
#define IDR_LINKMAN_SELALL              32803
#define IDR_LINKMAN_SELOTHER            32804
#define IDR_LINKMAN_EDITCARD            32805
#define IDR_SMS_COPY                    32806
#define ID_MENU_UNCONNECT               32807
#define ID_MENU_SWITCH                  32810
#define IDR_MENU_CLOSE                  32811
#define IDR_MENU_HELPINFO               32814
#define ID_MENU_ABOUT                   32815
#define IDR_MENU_UPDATE                 32816
#define IDR_MENU_ADDLINKMAN             32817
#define IDR_MENU_INPUTLINKMAN           32818
#define IDR_MENU_OUTPUTLINKMAN          32819
#define IDR_MENU_SET                    32820
#define IDR_SMS_RECV                    32821
#define IDR_SMS_RECVALL                 32822
#define IDM_DELETE                      32823
#define IDR_SEL_ALLCARD                 32823
#define IDM_CLEAR                       32824
#define IDR_RETURN_CARD                 32824
#define IDR_LINKMAN_OUTPUT              32825
#define IDR_LINKMAN_INPUT               32826
#define ID_MENUITEM32827                32827
#define ID_SYN_TO_OUTLOOK               32827
#define ID_MENUITEM32828                32828
#define ID_SYN_FROM_OUTLOOK             32828
#define ID_SYN_TO_OO                    32829
#define ID_SYN_FROM_OO                  32830
#define IDM_AUTO_UPDATE                 32831
#define IDM_ACCELERATE_LINK             32832
#define IDM_ACCELERATE_SET              32833
#define IDM_ACCELERATE_POPUP            32834
#define IDR_MENU_NETWORK                32834
#define IDM_ACCELERATE_ENABLE           32835
#define IDM_ACCELERATE_DISABLE          32837
#define IDM_ACCELERATE_STAT             32838
#define IDM_ACCELERATE_CAPABILITY       32839
#define IDS_MSG_NETLINK                 32840
#define IDS_CONNECT_EVDO                32841
#define IDS_DISCONNECT_EVDO             32842
#define IDS_CONNECTING_1X               32843
#define IDS_CONNECTING_EVDO             32844
#define IDC_BUTTON_PINOK                32846
#define IDC_BUTTON_PINCANCEL            32848
#define IDC_TEXT_PINCODE                32849
#define IDC_PIN_REMAINING               32850
#define IDC_STATIC_PINCODE              32851
#define IDC_STATIC_PUKCODE              32852
#define IDC_STATIC_PINREMAINING         32853
#define IDC_STATIC_INPUTPINLENERROR     32854
#define IDC_STATIC_INPUTPUKLENERROR     32855
#define IDC_STATIC_INPUTPINERROR        32856
#define IDC_STATIC_INPUTPUKERROR        32857
#define IDC_STATIC_UNLOCKPUKSUCC        32858
#define IDC_PINDIALOG_WINTEXT           32859
#define IDC_MSG_SMSSENDLENLONG          32860
#define IDR_NETWORKTYPE_CDMA            32861
#define IDR_NETWORKTYPE_HDR             32862
#define IDR_NETWORKTYPE_HYBRID          32863
#define IDS_MENU_CDMA                   32864
#define IDS_MENU_HDR                    32865
#define IDS_MENU_HYBRID                 32866

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        320
#define _APS_NEXT_COMMAND_VALUE         32835
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
