#ifndef FRAMEWIDGET_RES_H
#define FRAMEWIDGET_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor


#define FRAMEWIDGET_RES_FILE "framewidget.mif"

#ifndef IDS_MIF_COMPANY
#define IDS_MIF_COMPANY	6
#endif  // IDS_MIF_COMPANY

#ifndef IDS_MIF_COPYRIGHT
#define IDS_MIF_COPYRIGHT	7
#endif  // IDS_MIF_COPYRIGHT

#ifndef IDS_MIF_VERSION
#define IDS_MIF_VERSION	8
#endif  // IDS_MIF_VERSION

#define IDS_STRING_20	20
#define IDS_STRING_40	40

#endif  // FRAMEWIDGET_RES_H
