#ifndef _V8_REG_H_
#define _V8_REG_H_

#define DAVINCI_INTERRUPT_REG_BASE          0x60050000

#define DAVINCI_SIA2B_ST        (DAVINCI_INTERRUPT_REG_BASE + 0x20B0)
#define DAVINCI_SIA2B_EN        (DAVINCI_INTERRUPT_REG_BASE + 0x20B4)
#define DAVINCI_SIB2A_ST        (DAVINCI_INTERRUPT_REG_BASE + 0x20B8)
#define DAVINCI_SIB2A_EN        (DAVINCI_INTERRUPT_REG_BASE + 0x20BC)
#define DAVINCI_INTCRTL         (DAVINCI_INTERRUPT_REG_BASE + 0x000000)
#define DAVINCI_VECADDR     (DAVINCI_INTERRUPT_REG_BASE + 0x000004)
#define DAVINCI_RSDCNT          (DAVINCI_INTERRUPT_REG_BASE + 0x000008)
#define DAVINCI_SIA2B_ST        (DAVINCI_INTERRUPT_REG_BASE + 0x20B0)
#define DAVINCI_SIA2B_EN        (DAVINCI_INTERRUPT_REG_BASE + 0x20B4)
#define DAVINCI_SIB2A_ST        (DAVINCI_INTERRUPT_REG_BASE + 0x20B8)
#define DAVINCI_SIB2A_EN        (DAVINCI_INTERRUPT_REG_BASE + 0x20BC)
#define DAVINCI_BIUIRQST        (DAVINCI_INTERRUPT_REG_BASE + 0x1008)
#define DAVINCI_TEST            (DAVINCI_INTERRUPT_REG_BASE + 0x3000)
#define DAVINCI_BIUINTEN        (DAVINCI_INTERRUPT_REG_BASE + 0x101C)
#define DAVINCI_1LvINTClr       (DAVINCI_INTERRUPT_REG_BASE + 0x1020)
#define DAVINCI_INTSLCT         (DAVINCI_INTERRUPT_REG_BASE + 0x1014)
#define DAVINCI_MARB_ST     (DAVINCI_INTERRUPT_REG_BASE + 0x2000)



// 820 Hardware related macro defination
#define DAVINCI_INTEN               1
#define DAVINCI_FIQEN               (1<<2)
#define CYGNUM_HAL_INTERRUPT_SIA2B      22
#define CYGNUM_HAL_INTERRUPT_SIB2A      23

#define DAVINCI_BIULOWLEVEL     0x00000
#define DAVINCI_BIUHIGHLEVEL        0x00010
#define DAVINCI_BIUFALEDGE          0x00020
#define DAVINCI_BIURISEDGE          0x00040
#define DAVINCI_BIU_MODE            DAVINCI_BIULOWLEVEL

#define DAVINCI_HIRQEN              (1<<1)//by sunlei for test 1220
#define DAVINCI_BIUIRQEN            (1<<3)
#define DAVINCI_MODE                (0<<4)          //0=MMP,1=AP

#define CONFIG_4_BIU                (0xf9<<8)   //low level

#define V8_REG_TIMER_REG_BASE			0x60010000

//-----------------------------------------------------------------------------
// TIMER CTRL

#define V8_REG_TIMER_TMRCTRL			(V8_REG_TIMER_REG_BASE + 0x0508)
#define V8_REG_TIMER_TMRBASE			(V8_REG_TIMER_REG_BASE + 0x050C)
#define V8_REG_TIMER_TMR1TGT			(V8_REG_TIMER_REG_BASE + 0x0510)
#define V8_REG_TIMER_TMR2TGT			(V8_REG_TIMER_REG_BASE + 0x0514)
#define V8_REG_TIMER_TMR1DOUT		(V8_REG_TIMER_REG_BASE + 0x0518)
#define V8_REG_TIMER_TMR2DOUT		(V8_REG_TIMER_REG_BASE + 0x051C)
#define V8_REG_TIMER_WDOGTGT			(V8_REG_TIMER_REG_BASE + 0x0500)
#define V8_REG_TIMER_WDOGDOUT		(V8_REG_TIMER_REG_BASE + 0x0504)
	

#endif //_V8_RDK_BIU_H_

