# ############################################### #
# GNU Make file for forms
#
# Mandatory Vars to be exported from here
#	PROJECT,DIRDEPTH
# ############################################### #

# -- the target
export PROJECT=forms
export DIRDEPTH = ..

WIDGETSDIR=../widgets

# -- additional lint suppression files
LINT_SUPPRESSION_FILES=$(WIDGETSDIR)/lint/_project.lnt

### include generic makefile ###
include $(DIRDEPTH)/ext.mak
